export const generateImageAlt = (address, propertyType, city, visualDescription = '') => {
  const parts = [address, propertyType, 'in', city, 'CA'];
  if (visualDescription) parts.push('—', visualDescription);
  return parts.join(' ');
};

export const generatePropertyImageAlt = (property, index = 0) => {
  const visual = index === 0 ? 'front view' : index === 1 ? 'side view' : 'detail';
  return generateImageAlt(property.address, property.type || 'property', property.city, visual);
};

export const getImageResponsive = (imagePath, alt, width, height) => ({
  src: imagePath,
  alt,
  width,
  height,
  loading: 'lazy',
  decoding: 'async',
});

// Property photos also ship as WebP variants (400/800 px) generated by
// `npm run images` into public/assets/optimized/property/<stem>-<width>.webp.
// Deriving the paths from the source name is deliberate: it keeps a
// thousand-entry manifest out of the JS bundle. The original file stays as the
// <img> src fallback, and anything without a generated variant (street-view
// shots, sold-property art) simply passes through unchanged.
export const PROPERTY_VARIANT_WIDTHS = [400, 800];

export const propertyVariants = (src, widths = PROPERTY_VARIANT_WIDTHS) => {
  if (typeof src !== 'string') return null;
  const match = /^\/assets\/property\/(.+)\.(?:jpe?g|png)$/i.exec(src);
  if (!match) return null;
  return widths.map(w => ({ src: `/assets/optimized/property/${match[1]}-${w}.webp`, w }));
};

/** Spread straight onto an <img>: right-sized WebP on phones, original as fallback. */
export const responsiveImage = (src, { sizes = '100vw', widths = PROPERTY_VARIANT_WIDTHS } = {}) => {
  const variants = propertyVariants(src, widths);
  if (!variants) return { src };
  return {
    src,
    srcSet: variants.map(v => `${v.src} ${v.w}w`).join(', '),
    sizes,
  };
};

