import {useState,useEffect,useRef} from 'react';
import {ArrowRight,HouseLine,Hammer,ChartLineUp,InstagramLogo,YoutubeLogo,LinkedinLogo,List,X,Phone,Envelope} from '@phosphor-icons/react';
const services=[{title:'Real Estate',image:'house',Icon:HouseLine,copy:'Finding opportunities others miss.',detail:'Buying or selling in Bakersfield, Tehachapi, or Kern County? Start with a conversation about your property, priorities, and next move.'},{title:'Development',image:'development',Icon:Hammer,copy:'Adding value through smart construction and renovation.',detail:'Explore your property’s potential with a practical conversation about construction, renovation, and improvements that create lasting value.'},{title:'Investing',image:'investing',Icon:ChartLineUp,copy:'Strategic moves for long-term growth.',detail:'Discuss your goals, the numbers, and the bigger picture with a long-term approach to real estate investing.'}];
export function App(){
 const [menu,setMenu]=useState(false),[topic,setTopic]=useState(null);const dialog=useRef(null);
 useEffect(()=>{if(topic){dialog.current.showModal();document.body.style.overflow='hidden'}else{dialog.current.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[topic]);
 const contact=(title='Let’s talk',copy='Tell Nate what you have in mind. Call or email to start the conversation.')=>{setTopic({title,copy});setMenu(false)};
 return <><a className="skip" href="#main">Skip to content</a><header id="home"><a className="brand" href="#home" aria-label="Harbison Standard home"><img src="/assets/logo.webp" alt="Harbison Standard — Real Estate · Development · Investing"/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu}>{menu?<X/>:<List/>}</button><nav className={menu?'open':''} aria-label="Main navigation"><a className="active" href="#home" onClick={()=>setMenu(false)}>Home</a><a href="#approach" onClick={()=>setMenu(false)}>Our Approach</a><button onClick={()=>contact('Find your next property','Tell Nate what you’re looking for — location, budget, and the kind of property you have in mind.')}>Properties</button><a href="#about" onClick={()=>setMenu(false)}>About</a><button onClick={()=>contact()}>Contact</button></nav><button className="gold header-cta" onClick={()=>contact()}>Let’s talk</button></header>
 <main id="main"><section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Real estate. Real experience.</p><h1 id="hero-title">Know what<br/>you’re <em>looking at.</em></h1><div className="rule"/><p className="intro">Nathanael Harbison brings firsthand knowledge<br className="desktop"/> across real estate, construction, renovation,<br className="desktop"/> investing and development.</p><p className="motto">It’s not what you do,<br/><em>it’s how you do it.</em></p><div className="hero-actions"><button className="gold" onClick={()=>contact()}>Let’s talk <ArrowRight/></button><button className="text-link" onClick={()=>contact('Find your next property','Tell Nate what you’re looking for — location, budget, and the kind of property you have in mind.')}><span>View Properties</span><ArrowRight/></button></div></div><aside className="location"><strong>Same<br/>mountains.<br/>Bigger<br/>opportunities.</strong><div className="rule"/><p>Tehachapi<br/>Kern County<br/>California</p></aside></section>
 <section id="about" className="about"><div><p className="eyebrow">From the ground up.</p><h2>More than deals.<br/>A <em>higher standard.</em></h2></div><p>We find the right properties, improve them the right way, and create long-term value. Grounded in real-world experience, market knowledge, and a hands-on approach you won’t find in a spreadsheet.</p></section>
 <section className="services" aria-label="Our services">{services.map(({title,image,Icon,copy,detail})=><article key={title}><img className="service-photo" src={'/assets/'+image+'.webp'} alt={title==='Real Estate'?'California stucco home with landscaped front yard':title==='Development'?'Timber framing inside a home under construction':'City skyline beneath mountains at sunset'}/><div className="service-body"><Icon weight="thin" className="service-icon"/><div><h3>{title}</h3><p>{copy}</p><button className="learn" onClick={()=>contact(title,detail)}><span>Learn more</span><ArrowRight/></button></div></div></article>)}</section>
 <section id="approach" className="process"><div><p className="eyebrow">Our process</p><h2>Clarity at<br/><em>every turn.</em></h2></div><ol>{[{name:'Evaluate',copy:'Understand the property, the numbers, and the bigger picture.'},{name:'Execute',copy:'Improve with discipline and attention to detail.'},{name:'Create Value',copy:'Sell or hold — always with a long-term mindset.'}].map((step,i)=><li key={step.name}><span className="number">0{i+1}</span>{i<2&&<ArrowRight className="step-arrow" weight="thin"/>}<h3>{step.name}</h3><p>{step.copy}</p></li>)}</ol></section>
 <section className="closing"><a href="#home"><img className="footer-logo" src="/assets/logo.webp" alt="Harbison Standard"/></a><div><p className="motto">It’s not what you do,<br/><em>it’s how you do it.</em></p><button className="gold" onClick={()=>contact()}>Let’s talk <ArrowRight/></button></div></section></main><footer><p>Bakersfield · Tehachapi · Kern County · California</p><div className="socials">{[{Icon:InstagramLogo,name:'Instagram'},{Icon:YoutubeLogo,name:'YouTube'},{Icon:LinkedinLogo,name:'LinkedIn'}].map(({Icon,name})=><button key={name} aria-label={'Ask Nate about '+name} onClick={()=>contact('Connect with Nate','Call or email Nate for his latest updates and social media links.')}><Icon weight={name==='Instagram'?'regular':'fill'}/></button>)}<span/></div></footer>
 <dialog ref={dialog} onCancel={()=>setTopic(null)} onClick={e=>{if(e.target===dialog.current)setTopic(null)}} aria-labelledby="contact-title"><button className="close" aria-label="Close contact" onClick={()=>setTopic(null)}><X/></button><p className="eyebrow">Harbison Standard</p><h2 id="contact-title">{topic?.title}</h2><p>{topic?.copy}</p>{topic?.title==='Find your next property'&&<div className="property-gallery"><img src="/assets/property-one.webp" alt="Hillside home at sunset"/><img src="/assets/property-two.webp" alt="Single-story home"/><img src="/assets/property-front.webp" alt="Home overlooking the valley"/><small>Property photos · Ask Nate about current availability.</small></div>}<div className="nate-profile"><img src="/assets/headshot.webp" alt="Nathanael Harbison"/><span>Nathanael Harbison<br/><small>Real estate. Real experience.</small></span></div><a className="contact-option" href="tel:+16614727499"><Phone/> (661) 472-7499</a><a className="contact-option" href={'mailto:nate85.realtor@gmail.com?subject='+encodeURIComponent(topic?.title||'Harbison Standard inquiry')}><Envelope/> nate85.realtor@gmail.com</a><small>Nathanael Harbison · Kern County, California</small></dialog></>;
}
