export const agent = {
  name: 'Nathanael Harbison',
  email: 'nate85.realtor@gmail.com',
  phone: '(661) 472-7499',
  phoneHref: 'tel:+166****7499',
  smsHref: 'sms:+166****7499',
  license: '02059393',
  responseTime: 'within 24 hours',
  youtube: 'https://www.youtube.com/@Nathanaelharbison',
};
export const socials = [
  {name: 'Facebook', url: 'https://www.facebook.com/nate85.realtor'},
  {name: 'Instagram', url: 'https://www.instagram.com/nathanaelharbison'},
  {name: 'YouTube', url: 'https://www.youtube.com/@Nathanaelharbison'},
  {name: 'LinkedIn', url: 'https://www.linkedin.com/in/nathanael-harbison'},
];
// Verified property records and new active listings, collected 2026-09-19.
// Newest listings appear first. Past transactions can include either side of a sale.
// Listing courtesy attribution remains with the original listing agent/brokerage.
export const properties = [
  {id:'21204-stage-dr',slug:'21204-stage-dr',imageUrl:'/assets/property/21204-stage-dr-1.jpg',images:Array.from({length:24},(_,i)=>`/assets/property/21204-stage-dr-${i+1}.jpg`),address:'21204 Stage Dr',city:'Tehachapi',zip:'93561',region:'Kern County',price:499900,beds:4,baths:2,sqft:1945,date:'2026-08-21',lot:'0.48 acres',status:'Available',attribution:'Listing courtesy of Descygene Simunovich, Miramar Intl Tehachapi.',sourceMls:'9994415',context:'Brand new construction in West Golden Hills - 4 bed, 2 bath, 1,945 sq ft with paid solar and Presidential composition roof.',description:'Brand New Construction in West Golden Hills! This beautiful 4 bedroom, 2 bath home offers approximately 1,945 sq. ft. on a spacious .48 acre lot. The desirable split-wing floor plan features luxury vinyl plank flooring, a stylish kitchen with soft-close cabinetry and a walk-in pantry, plus a spacious interior laundry room. The primary suite includes a beautifully tiled shower and two walk-in closets. Additional highlights include an oversized attached 2 car garage, Presidential style composition roof, and paid off solar.',features:['New construction 2026','Paid-off solar','Oversized 2-car garage','Presidential composition roof']},
  {id:'18211-sulky-ln',slug:'18211-sulky-ln',imageUrl:'/assets/property/18211-sulky-ln-1.jpg',images:Array.from({length:45},(_,i)=>`/assets/property/18211-sulky-ln-${i+1}.jpg`),address:'18211 Sulky Ln',city:'Tehachapi',zip:'93561',region:'Kern County',price:499000,beds:3,baths:3,sqft:2496,date:'2026-09-14',lot:'0.27 acres',status:'Available',attribution:'Listing courtesy of Heather McKinley, Keller Williams Tehachapi.',sourceMls:'9994314',context:'Modern Stallion Springs residence - 3 bed, 3 bath, nearly 2,500 sq ft with chef\'s kitchen and spa-inspired primary suite.',description:'Luxury, convenience, and low-maintenance living come together in this beautifully crafted Stallion Springs home. Built in 2018, this beautifully designed residence offers 3 bedrooms, 3 bathrooms, and nearly 2,500 square feet of thoughtfully planned living space. Soaring ceilings, abundant natural light, and an open-concept floor plan create an inviting atmosphere for both everyday living and entertaining. The spacious great room flows seamlessly into the stunning chef\'s kitchen, complete with beautiful cabinetry, generous prep space, a large center island, and modern finishes.',features:['Built 2018','Open-concept floor plan','Chef\'s kitchen with island','Spa-inspired primary suite']},
  {id:'28211-seabiscuit-way',slug:'28211-seabiscuit-way',imageUrl:'/assets/property/28211-seabiscuit-way-1.jpg',images:Array.from({length:36},(_,i)=>`/assets/property/28211-seabiscuit-way-${i+1}.jpg`),address:'28211 Seabiscuit Way',city:'Tehachapi',zip:'93561',region:'Kern County',price:699000,beds:4,baths:3,sqft:2836,date:'2026-08-29',lot:'0.75 acres',status:'Available',attribution:'Listing courtesy of Adonae Faris, Tehachapi Summit Real Estate.',sourceMls:'9994413',context:'Spacious Stallion Springs home - 4 bed, 3 bath, 2,836 sq ft with paid solar + battery, 3-car garage, and outdoor fire pit and waterfall.',description:'Welcome to this exceptional Stallion Springs home offering space, privacy, thoughtful design, and freedom. With approximately 2,836 square feet, 4 bedrooms, 3 bathrooms, and a spacious 3 car garage, this beautifully appointed residence offers the perfect blend of mountain living and modern comfort. The expansive primary suite is a true retreat, featuring vaulted ceilings, walk-in closet and separate 2nd closet, a luxurious soaking tub, and large walk-in shower. The home also has a tankless water heater, central vacuum, and fully paid-off solar system with panels and battery storage.',features:['Paid-off solar + battery','3-car garage','Outdoor fire pit & waterfall','EV charger']},
  {id:'28751-gleneagle-ct',slug:'28751-gleneagle-ct',imageUrl:'/assets/property/28751-gleneagle-ct-1.jpg',images:Array.from({length:45},(_,i)=>`/assets/property/28751-gleneagle-ct-${i+1}.jpg`),address:'28751 Gleneagle Ct',city:'Tehachapi',zip:'93561',region:'Kern County',price:499999,beds:3,baths:2.5,sqft:2364,date:'2026-09-12',lot:'0.47 acres',status:'Available',attribution:'Listing courtesy of Chrystle Deal & Monique Weese, LRS Realty & Management, Inc.',sourceMls:'202603588',context:'Stallion Springs mountain home - 3 bed, 2.5 bath with floor-to-ceiling windows and sweeping views.',description:'Welcome to 28751 Gleneagle Ct, an exceptional Stallion Springs residence offering sweeping mountain views and refined living in a serene setting. This thoughtfully designed home features 3 bedrooms, 2.5 bathrooms, and a versatile bonus room ideal for an office, gym, or guest retreat. The primary suite offers private deck access, a walk-in closet, and picturesque views. The great room is highlighted by dramatic floor-to-ceiling windows that fill the home with natural light.',features:['Floor-to-ceiling windows','Mountain views','Oversized 3-car garage','Greenhouse']},
  {id:'958-fairway-dr',slug:'958-fairway-dr',imageUrl:'/assets/property/958-fairway-dr-1.jpg',images:Array.from({length:64},(_,i)=>`/assets/property/958-fairway-dr-${i+1}.jpg`),address:'958 Fairway Dr',city:'Bakersfield',zip:'93309',region:'Kern County',price:899900,beds:4,baths:3,sqft:2170,date:'2026-08-21',lot:'10,744 sq ft',status:'Available',attribution:'Listing courtesy of Cecilia Clark, Emerge Real Estate.',sourceMls:'OC26184352',context:'Fully renovated Stockdale Country Club gem - 4 bed, 3 bath with dual en-suites and renovated pool.',description:'Welcome to this beautifully renovated 4-bedroom, 3-bathroom home nestled in the prestigious Stockdale Country Club. A brand new Presidential roof, updated 200-amp electrical panel, and renovated pool mean the big ticket items are already taken care of. Inside, the fully renovated interior delivers a fresh, modern feel throughout, complemented by a desirable dual en-suite layout offering two private bedroom and bathroom combinations, perfect for multigenerational living or hosting guests in style.',features:['Stockdale Country Club','Dual en-suite layout','Renovated pool','New Presidential roof']},
  {id:'2300-weybridge-dr',slug:'2300-weybridge-dr',imageUrl:'/assets/property/2300-weybridge-dr-1.jpg',images:Array.from({length:73},(_,i)=>`/assets/property/2300-weybridge-dr-${i+1}.jpg`),address:'2300 Weybridge Dr',city:'Bakersfield',zip:'93311',region:'Kern County',price:2895000,beds:5,baths:8,sqft:7025,date:'2026-07-15',lot:'19,602 sq ft',status:'Available',attribution:'Listing courtesy of William Gordon, Watson Realty.',sourceMls:'V137657',context:'Magnificent Seven Oaks estate - 5 bed, 8 bath, 7,025+ sq ft with $1M+ remodel and golf course views.',description:'Stunning 7,000+ sq ft estate with $1,000,000+ remodel! Situated on the 9th hole of the Islands course, you are only a short walk from the Seven Oaks clubhouse. One of the most striking features is the refinished wood flooring, cabinetry, coffered ceilings and banisters, particularly in the study, foyer and staircase. The gourmet kitchen has high-end Wolf appliances and premier custom cabinets. The owner\'s suite is located on the ground floor with its 3 walk-in closets plus sitting area and direct access to the back yard spa. 4 ensuite bedrooms upstairs, all with walk-in closets. Finished walk-out basement used as gym/storage. Owned solar system and elevator with access to all three floors.',features:['Seven Oaks gated','Golf course views','Elevator','Owned solar','Wolf appliances']},
  {id:'2206-ribble-valley-dr',slug:'2206-ribble-valley-dr',imageUrl:'/assets/property/2206-ribble-valley-dr-1.jpg',images:Array.from({length:64},(_,i)=>`/assets/property/2206-ribble-valley-dr-${i+1}.jpg`),address:'2206 Ribble Valley Dr',city:'Bakersfield',zip:'93311',region:'Kern County',price:975000,beds:5,baths:3,sqft:3123,date:'2026-08-26',lot:'14,375 sq ft',status:'Available',attribution:'Listing courtesy of Jeff Jackson, Cal Connect Realty Group Inc.',sourceMls:'NS26187383',context:'Grand Island gated estate - 5 bed, 3 bath with waterfall pool and custom wrought-iron entry.',description:'Prestigious Gibbons & Wheelan home located in the gated Grand Island community at Seven Oaks. An elegant tiered stone-entry staircase, stacked-stone pillars, manicured landscaping, exposed rafter-tail eaves, and a rock-accented elevation create exceptional curb appeal. Custom double wrought-iron entry doors with hand-forged scrollwork welcome you inside, where you\'ll find tray ceilings, custom 20-inch tile flooring, and a desirable three-way split-wing design. The granite kitchen features upscale custom cabinetry, a center island, a wine refrigerator, and a custom backsplash.',features:['Grand Island gated','Waterfall pool','Wrought-iron entry','Wine refrigerator']},
  {id:'2901-summit-cir',slug:'2901-summit-cir',imageUrl:'/assets/property/2901-summit-cir-1.jpg',images:Array.from({length:46},(_,i)=>`/assets/property/2901-summit-cir-${i+1}.jpg`),address:'2901 Summit Cir',city:'Bakersfield',zip:'93306',region:'Kern County',price:359000,beds:2,baths:1.75,sqft:2209,date:'2026-07-18',lot:'6,570 sq ft',status:'Available',attribution:'Listing courtesy of Bradley Barnett, Century 21 Select Real Estate.',sourceMls:'202607788',context:'Gated 55+ Summit Villas community - 2 bed with owned solar, clubhouse, and pool.',description:'Owned Solar. No Lease, No Loan! Discover easy, resort-like living in the unmatched Summit Villas, a gated 55+ community of only 12 custom homes. Residents enjoy a private clubhouse, sparkling pool, and a reservable guest house while the HOA maintains the community\'s shared amenities. This beautiful home offers approximately 2,209 square feet with abundant flexible-use spaces designed for comfortable living.',features:['55+ gated community','Owned solar','Private clubhouse','Community pool']},
  {id:'3109-mount-vernon-ave',slug:'3109-mount-vernon-ave',imageUrl:'/assets/property/3109-mount-vernon-ave-1.jpg',images:Array.from({length:29},(_,i)=>`/assets/property/3109-mount-vernon-ave-${i+1}.jpg`),address:'3109 Mount Vernon Ave',city:'Bakersfield',zip:'93306',region:'Kern County',price:299900,beds:4,baths:2,sqft:1680,date:'2026-09-18',lot:'8,276 sq ft',status:'Available',attribution:'Listing courtesy of Jorge Solis, Infinity Real Estate Services.',sourceMls:'202607149',context:'East Bakersfield investment opportunity with mother-in-law unit and tenant in place.',description:'Home features a dining room, breakfast area, large family room, laundry room, 1,680 sq ft of living space, Central Heat & Air, Alley Access, 4 bedrooms, 2 bathrooms, Spacious backyard 8,276 sq ft lot size plus a mother-in-law unit with its own kitchenette. The property is being sold with the tenant in place. The current long-term tenant pays $1,800 per month and is under a lease through October 31, 2026. No FHA financing; conventional or cash offers only.',features:['Mother-in-law unit','Tenant in place','$1,800/mo income','Alley access']},
  {id:'909-oberlin-ct',slug:'909-oberlin-ct',imageUrl:'/assets/property/909-oberlin-ct-1.jpg',images:Array.from({length:34},(_,i)=>`/assets/property/909-oberlin-ct-${i+1}.jpg`),address:'909 Oberlin Ct',city:'Bakersfield',zip:'93305',region:'Kern County',price:299900,beds:3,baths:2,sqft:1350,date:'2026-09-18',lot:'10,000 sq ft',status:'Available',attribution:'Listing courtesy of Jesus H Garcia, The Mora Partners Inc.',sourceMls:'202608755',context:'Updated East Bakersfield home on cul-de-sac with new roof, solar, and ADU potential.',description:'Welcome to this beautifully updated 3-bedroom, 2-bathroom home situated on a quiet cul-de-sac and set on an expansive 10,000-square-foot lot! Step inside to an inviting living area featuring recessed lighting, ceiling fans, and large windows that provide abundant natural light. The updated kitchen offers quartz countertops, a new sink, and modern lighting. Both bathrooms have been tastefully upgraded with new vanities, flooring, mirrors, and showers. Additional improvements include a new roof, solar panels, new electrical panel, wood fencing, recessed lighting, ceiling fans, and convenient indoor laundry.',features:['Quiet cul-de-sac','New roof & solar','Quartz countertops','ADU potential']},
  {id:'505-jeffrey-st',slug:'505-jeffrey-st',imageUrl:'/assets/property/505-jeffrey-st-1.jpg',images:Array.from({length:18},(_,i)=>`/assets/property/505-jeffrey-st-${i+1}.jpg`),address:'505 Jeffrey St',city:'Bakersfield',zip:'93305',region:'Kern County',price:287000,beds:2,baths:2,sqft:0,date:'2026-09-18',lot:'6,969 sq ft',status:'Available',attribution:'Listing courtesy of Karmen Domani, Real Broker.',sourceMls:'202608357',context:'Turnkey remodeled East Bakersfield with new plumbing, electrical, kitchen, and baths.',description:'Beautifully remodeled 2-bedroom, 2-bath home on an oversized lot in East Bakersfield. This move-in ready property has been extensively updated, including new plumbing and electrical, a new kitchen with updated cabinetry, countertops and fixtures, fully renovated bathrooms, new flooring, fresh interior and exterior paint, and updated lighting. The bright, functional floor plan maximizes the living space and offers a clean, modern feel throughout. The large lot provides exceptional outdoor space with room for entertaining, future improvements or potential ADU possibilities (buyer to verify).',features:['New plumbing & electrical','New kitchen','Renovated bathrooms','ADU potential']},
  {id:'wendy',imageUrl:'/assets/property/wendy1.jpg',images:Array.from({length:18},(_,i)=>`/assets/property/wendy${i+1}.jpg`),address:'585 N Wendy Dr',city:'Newbury Park',zip:'91320',region:'Ventura County',price:880000,beds:3,baths:2,sqft:1633,date:'2026-09-16',lot:'7,840 sq ft',status:'Available',context:'A fully reimagined Newbury Park residence with Boney Mountain views, chef\'s kitchen, 400+ sq ft bonus room, and top-rated schools.',description:'Welcome to a fully reimagined Newbury Park residence where designer finishes meet everyday livability, all framed by sweeping views of Boney Mountain. Step inside to find luxury vinyl plank flooring flowing throughout, setting the stage for a home that has been remodeled top to bottom with genuine attention to detail.'},
  {id:'mariposa',address:'22208 Mariposa Road',city:'Tehachapi',zip:'93561',region:'Kern County',price:40000,beds:0,baths:0,sqft:0,lot:'13,068 sq ft',date:'2026-09-16',status:'Available',context:'Prime Tehachapi land opportunity in Cummings Valley.',description:'Prime Tehachapi land opportunity ready for your future build for either a primary house or even multi family! This property offers the perfect blend of rural living and modern convenience.',images:[1,2,3,4,5,6].map(i=>`/assets/property/22208-mariposa-${i}.jpg`)},
  {id:'chalet',address:'Chalet Property',city:'Tehachapi',zip:'93561',region:'Kern County',price:199000,beds:0,baths:0,sqft:0,lot:'882,090 sq ft (20± acres)',date:'2026-09-16',status:'Available',context:'20-acre Cummings Valley property with owner financing available.',description:'20± acres in the Cummings Valley area with phenomenal views across the valley to the Tehachapi Mountains. Building pad already cleared, gated ranch entry in place, overhead power at the road, and an established access road to the site.',images:[1,2,3,4,5,6,7].map(i=>`/assets/property/chalet-tehachapi-${i}.jpg`)},
  {id:'pellisier',address:'18024 Pellisier Road',city:'Tehachapi',zip:'93561',region:'Kern County',price:980000,beds:4,baths:3,sqft:2805,date:'2025-07-01',lot:'20.08 acres',status:'Sold',context:'A unique mountain property with acreage, views, and a specific buyer profile.',description:'A mountain ranch with room to breathe. Set on more than 20 acres in Cummings Valley, this home brings together expansive views, a wraparound deck, and a barn with horse stalls.'},
  {id:'sheridan',address:'10618 Sheridan Street',city:'California City',zip:'93505',region:'Kern County',price:345000,beds:4,baths:2,sqft:1705,date:'2025-06-06',status:'Sold',context:'A spacious single-story home in California City',description:'A well-maintained single-story residence featuring 4 bedrooms, 2 bathrooms, and 1,705 sq ft of living space. This California City home combines affordability with comfortable family living.'},
  {id:'mendiburu',address:'9664 Mendiburu Road',city:'California City',zip:'93505',region:'Kern County',price:359000,beds:4,baths:2,sqft:2246,date:'2024-01-12',status:'Sold',context:'Renovation potential on an open lot in California City',description:'A 4-bedroom, 2-bathroom California City property offering 2,246 sq ft with solid bones and renovation potential.'},
  {id:'alsab',address:'17400 Alsab Place',city:'Stallion Springs',zip:'93561',region:'Kern County',price:390000,beds:3,baths:2,sqft:1507,date:'2023-10-30',status:'Sold',context:'A home in Stallion Springs with room to grow',description:'A 3-bedroom, 2-bathroom Stallion Springs residence with 1,507 sq ft of comfortable living space. This home sits in an established community known for family amenities.'},
  {id:'windsong',address:'21213 Windsong Street',city:'California City',zip:'93505',region:'Kern County',price:305000,beds:3,baths:2.5,sqft:1591,date:'2023-09-08',status:'Sold',context:'A starter-friendly home in California City',description:'An affordable 3-bedroom, 2.5-bathroom California City home offering 1,591 sq ft of accessible living space.'},
];
export const testimonials = [
  {quote:"Nathanael was honest, responsive, and easy to work with from start to finish. He understood what we were looking for and didn't waste our time with properties that didn't fit.",label:'Buyer · Bakersfield'},
  {quote:"We weren't sure whether to fix things up or sell as-is. Nathanael helped us think it through clearly and never made us feel pressured. We felt confident in our decision.",label:'Seller · Time-sensitive sale'},
  {quote:'Nathanael brought calm, clarity, and practical advice throughout the sale. We always felt like we understood what was happening and why.',label:'Seller · Kern County'},
  {quote:"After three years of ownership, we wanted guidance on whether to hold or sell. Nathanael laid out the numbers and let us decide. That straight talk is exactly what we needed.",label:'Investor · California City'},
  {quote:"Our inherited home felt overwhelming. Nathanael helped us understand the options and what the property was actually worth. We felt supported every step.",label:'Seller · Inherited property'},
  {quote:"Coming from Los Angeles, we didn't know the Bakersfield market. Nathanael showed us what our budget could actually buy and helped us understand the different neighborhoods.",label:'Buyer · Relocated from LA'},
];
export const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:Number.isInteger(Number(value))?0:2,maximumFractionDigits:2}).format(value);
export const soldDate = value => new Date(value+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
