export const agent = {
  name: 'Nathanael Harbison',
  email: 'nate85.realtor@gmail.com',
  phone: '(661) 472-7499',
  phoneHref: 'tel:+16614727499',
  smsHref: 'sms:+16614727499',
  license: '02059393',
  responseTime: 'within 24 hours',
  youtube: 'https://www.youtube.com/@Nathanaelharbison',
};
export const socials = [
  {name: 'Facebook', url: 'https://www.facebook.com/nate85.realtor'},
  {name: 'Instagram', url: 'https://www.instagram.com/nathanaelharbison'},
  {name: 'YouTube', url: 'https://www.youtube.com/@Nathanaelharbison'},
  {name: 'LinkedIn', url: 'https://www.linkedin.com/in/nathanael-harbison'},
];
// Verified past transactions and property records, 2026-09-06.
// Past transactions can include either side of a sale; do not label all as seller representation.
export const properties = [
  {id:'wendy',imageUrl:'/assets/property/wendy1.jpg',images:Array.from({length:18},(_,i)=>`/assets/property/wendy${i+1}.jpg`),address:'585 N Wendy Dr',city:'Newbury Park',zip:'91320',region:'Ventura County',price:880000,beds:3,baths:2,sqft:1633,date:'2026-09-16',lot:'7,840 sq ft',status:'Available',context:'A fully reimagined Newbury Park residence with Boney Mountain views, chef\'s kitchen, 400+ sq ft bonus room, and top-rated schools.',description:'Welcome to a fully reimagined Newbury Park residence where designer finishes meet everyday livability, all framed by sweeping views of Boney Mountain. Step inside to find luxury vinyl plank flooring flowing throughout, setting the stage for a home that has been remodeled top to bottom with genuine attention to detail. The showpiece kitchen features dramatic gold-and-black marbled quartz countertops, a professional KitchenAid gas range and oven, and a chef\'s pot filler — a space equally suited to weeknight dinners and holiday gatherings. The living room fireplace, wrapped in imported Italian veneer, anchors the main living space with warmth and sophistication, and the same Italian craftsmanship carries into both remodeled bathrooms, where fully tiled showers elevate the everyday routine. Outside, the covered rear patio is an entertainer\'s dream — finished in custom hexagon Italian tile and positioned to take in the peacefully robust landscaped yard. And then there\'s the surprise: a versatile bonus room off the garage spanning over 400 square feet — ideal as a home office, gym, studio, or media retreat. All of this sits minutes from the area\'s coveted International Baccalaureate middle and high school programs, plus trails, parks, shopping, and easy 101 access. Turnkey, timeless, and truly move-in ready — A rare remodel that feels like new construction.'},
  {id:'mariposa',address:'22208 Mariposa Road',city:'Tehachapi',zip:'93561',region:'Kern County',price:40000,beds:0,baths:0,sqft:0,lot:'13,068 sq ft',date:'2026-09-16',status:'Available',context:'Prime Tehachapi land opportunity in Cummings Valley. Perfect for custom home build, multi-family development, or investment property.',description:'Prime Tehachapi land opportunity ready for your future build for either a primary house or even multi family! This property offers the perfect blend of rural living and modern convenience, with close proximity to Highway 58, downtown Tehachapi, local restaurants, shopping, schools, and everyday amenities. Enjoy the open-space lifestyle Tehachapi is known for while still being minutes from town and commuter access. The property is positioned in a desirable location for a new custom home, with grading costs already estimated with local grading contractor. Additional information has also been acquired from Southern California Edison regarding utility details. Bring your builder and explore the potential this property offers for a primary residence, mountain retreat, or long-term investment on a 1/3 of an acre!',images:[1,2,3,4,5,6].map(i=>`/assets/property/22208-mariposa-${i}.jpg`)},
  {id:'chalet',address:'Chalet Property',city:'Tehachapi',zip:'93561',region:'Kern County',price:199000,beds:0,baths:0,sqft:0,lot:'882,090 sq ft (20± acres)',date:'2026-09-16',status:'Available',context:'20-acre Cummings Valley property with owner financing available. Cleared building pad, gated entry, overhead power, perfect for custom build or equestrian use.',description:'20± acres in the Cummings Valley area with phenomenal views across the valley to the Tehachapi Mountains. Building pad already cleared, gated ranch entry in place, overhead power at the road, and an established access road to the site. Room here for far more than a house — a large shop or barn for RVs, boats, trailers and equipment, plus corrals or outbuildings, subject to Kern County permitting. Zoned A (Exclusive Agriculture) and set well off the road for genuine privacy. Tehachapi\'s four distinct seasons bring green spring hillsides, dry summers, fall color and light winter snow. Deer are regular residents and elk move through seasonally. OWNER FINANCING AVAILABLE. Seller is a licensed CA general contractor and open to discussing a custom build under separate agreement.',images:[1,2,3,4,5,6,7].map(i=>`/assets/property/chalet-tehachapi-${i}.jpg`)},
  {id:'pellisier',address:'18024 Pellisier Road',city:'Tehachapi',zip:'93561',region:'Kern County',price:980000,beds:4,baths:3,sqft:2805,date:'2025-07-01',lot:'20.08 acres',status:'Sold',context:'A unique mountain property with acreage, views, and a specific buyer profile.',description:'A mountain ranch with room to breathe. Set on more than 20 acres in Cummings Valley, this home brings together expansive views, a wraparound deck, and a barn with horse stalls.'},
  {id:'sheridan',address:'10618 Sheridan Street',city:'California City',zip:'93505',region:'Kern County',price:345000,beds:4,baths:2,sqft:1705,date:'2025-06-06',status:'Sold',context:'A spacious single-story home in California City'},
  {id:'mendiburu',address:'9664 Mendiburu Road',city:'California City',zip:'93505',region:'Kern County',price:359000,beds:4,baths:2,sqft:2246,date:'2024-01-12',status:'Sold',context:'Renovation potential on an open lot in California City'},
  {id:'alsab',address:'17400 Alsab Place',city:'Stallion Springs',zip:'93561',region:'Kern County',price:390000,beds:3,baths:2,sqft:1507,date:'2023-10-30',status:'Sold',context:'A home in Stallion Springs with room to grow'},
  {id:'windsong',address:'21213 Windsong Street',city:'California City',zip:'93505',region:'Kern County',price:305000,beds:3,baths:2.5,sqft:1591,date:'2023-09-08',status:'Sold',context:'A starter-friendly home in California City'},
];
export const testimonials = [
  {quote:"Nathanael was honest, responsive, and easy to work with from start to finish. He understood what we were looking for and didn't waste our time with properties that didn't fit.",label:'Buyer · Bakersfield'},
  {quote:"We weren't sure whether to fix things up or sell as-is. Nathanael helped us think it through clearly and never made us feel pressured. We felt confident in our decision.",label:'Seller · Time-sensitive sale'},
  {quote:'Nathanael brought calm, clarity, and practical advice throughout the sale. We always felt like we understood what was happening and why.',label:'Seller · Kern County'},
  {quote:"After three years of ownership, we wanted guidance on whether to hold or sell. Nathanael laid out the numbers and let us decide. That straight talk is exactly what we needed.",label:'Investor · California City'},
  {quote:"Our inherited home felt overwhelming. Nathanael helped us understand the options and what the property was actually worth. We felt supported every step.",label:'Seller · Inherited property'},
  {quote:"Coming from Los Angeles, we didn't know the Bakersfield market. Nathanael showed us what our budget could actually buy and helped us understand the different neighborhoods.",label:'Buyer · Relocated from LA'},
];
export const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:Number.isInteger(Number(value))?0:2,maximumFractionDigits:2}).format(value);
export const soldDate = value => new Date(value+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
