import {ArrowRight,ArrowUpRight,YoutubeLogo,HouseLine,Hammer,ChartLineUp} from '@phosphor-icons/react';
import {agent} from './data';
import {LeadForm} from './LeadForm';
const services=[{title:'Sell Your Home',href:'/real-estate',image:'house',Icon:HouseLine,copy:'A way forward when life changes.'},{title:'Development',href:'/development',image:'development',Icon:Hammer,copy:'Build your home. Find a spec home.'},{title:'Investing',href:'/investing',image:'investing',Icon:ChartLineUp,copy:'Explore properties, company investing, and home flips.'}];

export function Home(){return <><section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Real estate. Real experience.</p><h1 id="hero-title">Know what<br/>you’re <em>looking at.</em></h1><div className="rule"/><p className="intro">Nathanael Harbison brings firsthand knowledge<br className="desktop"/> across real estate, construction, renovation,<br className="desktop"/> investing and development.</p><p className="motto">It’s not what you do,<br/><em>it’s how you do it.</em></p><div className="hero-actions"><button className="gold" onClick={()=>document.getElementById("inquiry").scrollIntoView({behavior:"smooth"})}>Let’s talk <ArrowRight/></button><a className="text-link" href="/properties"><span>View Properties</span><ArrowRight/></a></div></div><aside className="location"><strong>Same<br/>mountains.<br/>Bigger<br/>opportunities.</strong><div className="rule"/><p>Tehachapi<br/>Kern County<br/>California</p></aside></section>
 <section id="about" className="about"><div><p className="eyebrow">From the ground up.</p><h2>More than deals.<br/>A <em>higher standard.</em></h2></div><p>We find the right properties, improve them the right way, and create long-term value. Grounded in real-world experience, market knowledge, and a hands-on approach you won’t find in a spreadsheet. <a className="inline-link" href="/about">Meet Nathanael <ArrowRight/></a><br/><a className="inline-link" href={agent.youtube} target="_blank" rel="noreferrer"><YoutubeLogo/> See the work on YouTube <ArrowUpRight/></a></p></section>
 <section className="services" aria-label="Our services">{services.map(({title,href,image,Icon,copy})=><article key={title}><a className="service-card-link" href={href}><img className="service-photo" src={'/assets/'+image+'.webp'} alt={title==='Sell Your Home'?'California stucco home with landscaped front yard':title==='Development'?'Timber framing inside a home under construction':'City skyline beneath mountains at sunset'}/><div className="service-body"><Icon weight="thin" className="service-icon"/><div><h3>{title}</h3><p>{copy}</p><span className="learn"><span>Learn more</span><ArrowRight/></span></div></div></a></article>)}</section>
 <section id="approach" className="process"><div><p className="eyebrow">Our process</p><h2>Clarity at<br/><em>every turn.</em></h2></div><ol>{[{name:'Evaluate',copy:'Understand the property, the numbers, and the bigger picture.'},{name:'Execute',copy:'Improve with discipline and attention to detail.'},{name:'Create Value',copy:'Sell or hold — always with a long-term mindset.'}].map((step,i)=><li key={step.name}><span className="number">0{i+1}</span>{i<2&&<ArrowRight className="step-arrow" weight="thin"/>}<h3>{step.name}</h3><p>{step.copy}</p></li>)}</ol></section>
 <section id="inquiry" className="inquiry-section"><div><p className="eyebrow">Your next chapter</p><h2>Good things start<br/>with <em>a conversation.</em></h2><p>Buying your first home, planning a sale, or seeing potential in a property? Tell Nate what you have in mind.</p><a className="inline-link" href="/contact">Contact Nate directly <ArrowRight/></a></div><LeadForm source="Homepage"/></section></>;}
