import {ArrowRight,ArrowUpRight,YoutubeLogo,Phone,MapPin,SealCheck,UsersThree,PhoneCall,Hammer,HouseLine,ChartLineUp} from '@phosphor-icons/react';
import {agent,properties,money,soldDate,testimonials} from './data';
import {homeFaq} from './seo';
import {LeadForm} from './LeadForm';
const trust=[{Icon:SealCheck,text:'REALTOR® · DRE #02059393'},{Icon:MapPin,text:'Serving Kern County'},{Icon:Hammer,text:'Construction background since 2017'},{Icon:UsersThree,text:'Buyer, seller & investor guidance'},{Icon:PhoneCall,text:'Call or text direct'}];
const services=[{title:'Sell Your Home',href:'/real-estate',image:'house',Icon:HouseLine,copy:'A thoughtful approach to timing, repairs, pricing, and next steps.',learn:'Learn about selling'},{title:'Development',href:'/development',image:'development',Icon:Hammer,copy:'Explore land, spec homes, or what it could take to build from the ground up.',learn:'Explore development'},{title:'Investing',href:'/investing',image:'investing',Icon:ChartLineUp,copy:'Talk through investment properties, flips, and opportunities with a practical eye.',learn:'Explore investing'}];
const reasons=[['01','Builder’s perspective','A more informed eye for property condition, repairs, and potential.'],['02','Straightforward advice','Clear communication without pressure or unnecessary complexity.'],['03','Multiple types of experience','Support for buyers, sellers, investors, and people exploring new construction.'],['04','Local understanding','Grounded knowledge of Kern County, Tehachapi, and surrounding communities.']];
const areas=['Tehachapi','California City','Bakersfield','Stallion Springs','Delano','Lake Isabella'];
const steps=[{name:'Start with a conversation',copy:'Share your situation, questions, or property goals.'},{name:'Look at the details',copy:'Review the property, timing, numbers, and practical considerations.'},{name:'Decide on the right move',copy:'Create a plan that fits your goals, whether that means buying, selling, building, or waiting.'}];

export function Home(){
 const featured=properties[0];
 return <>
  <section className="hero hero--standard" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Real estate. Real experience.</p><h1 id="hero-title">Real estate guidance<br/>with a <em>builder’s eye.</em></h1><div className="rule"/><p className="intro">Helping buyers, sellers, and investors across Kern County with practical real estate experience in construction, renovation, development, and property value.</p><div className="hero-actions"><a className="gold" href={agent.phoneHref}><Phone/> Call Nathanael</a><a className="text-link" href="/properties"><span>View Past Sales</span><ArrowRight/></a><a className="text-link text-link--small" href="#services"><span>Explore Services</span><ArrowRight/></a></div></div><aside className="location"><strong>Same<br/>mountains.<br/>Bigger<br/>opportunities.</strong><div className="rule"/><p>Tehachapi<br/>Kern County<br/>California</p></aside></section>
  <section className="trust-bar" aria-label="Credentials and service areas"><ul>{trust.map(({Icon,text})=><li key={text}><Icon weight="fill"/><span>{text}</span></li>)}</ul></section>
  <section className="home-about"><div><p className="eyebrow">More than a transaction</p><h2>A higher standard<br/>for <em>your next move.</em></h2></div><p>Whether you’re buying, selling, building, or exploring an investment, the right decision starts with understanding the property in front of you. Nathanael brings a practical perspective shaped by hands-on construction experience, real estate work, and a long-term view of value. <a className="inline-link" href="/about">Meet Nathanael <ArrowRight/></a><a className="inline-link" href={agent.youtube} target="_blank" rel="noreferrer"><YoutubeLogo/> Follow Nathanael’s builds on YouTube <ArrowUpRight/></a></p></section>
  <section id="services" className="services" aria-label="Our services">{services.map(({title,href,image,Icon,copy,learn})=><article key={title}><a className="service-card-link" href={href}><img className="service-photo" src={'/assets/'+image+'.webp'} alt={title==='Sell Your Home'?'California stucco home with landscaped front yard':title==='Development'?'Timber framing inside a home under construction':'City skyline beneath mountains at sunset'}/><div className="service-body"><Icon weight="thin" className="service-icon"/><div><h3>{title}</h3><p>{copy}</p><span className="learn"><span>{learn}</span><ArrowRight/></span></div></div></a></article>)}</section>
  <section className="expertise-section page-wrap"><div className="section-heading"><div><p className="eyebrow">Why Harbison Standard</p><h2>Practical guidance.<br/><em>Direct communication. Real experience.</em></h2></div><p>How clients get more out of the process — not just the listing.</p></div><div className="expertise-grid">{reasons.map(([n,title,copy])=><article key={title}><span className="number">{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="featured-property page-wrap" aria-label="Featured past sale"><div className="property-image"><img src={'/assets/sold/'+featured.id+'.webp'} alt={featured.address+', '+featured.city} loading="eager"/><span className="sold-badge">Sold</span></div><div className="featured-copy"><p className="eyebrow">Recent result · Tehachapi</p><p className="featured-price">{money(featured.price)}</p><h2>{featured.address}</h2><p className="property-location">{featured.city}, CA {featured.zip}</p><div className="property-facts"><span>{featured.beds} beds</span><span>{featured.baths} baths</span><span>{featured.sqft.toLocaleString('en-US')} sq ft</span></div><p className="property-description">A unique ranch property with acreage, views, and a specific buyer profile. Properties like this benefit from thoughtful positioning, strong presentation, and a clear understanding of what matters most to likely buyers.</p><p className="sale-date">Sold {soldDate(featured.date)} · {featured.lot}</p><a className="inline-link" href="/properties">See More Past Sales <ArrowRight/></a></div></section>
  <section className="testimonial-section"><div className="svc-head"><div><p className="eyebrow">Trusted along the way</p><h2>What clients <em>appreciate most.</em></h2></div></div><div className="testimonial-grid">{testimonials.map(t=><article className="testimonial-card" key={t.label}><blockquote><p>“{t.quote}”</p></blockquote><p className="t-label">{t.label}</p></article>)}</div></section>
  <section className="svc"><div className="svc-head"><div><p className="eyebrow">Areas served</p><h2>Serving clients across <em>Kern County.</em></h2></div><p>Including the communities below and the surrounding areas.</p></div><div className="areas">{areas.map(a=><span key={a}>{a}</span>)}</div></section>
  <section className="svc svc--tint"><div className="svc-head"><div><p className="eyebrow">Common questions</p><h2>Quick answers,<br/><em>before you reach out.</em></h2></div><p>Straight answers to the questions buyers, sellers, builders, and investors ask most.</p></div><div className="faq">{homeFaq.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></section>
  <section id="approach" className="process"><div><p className="eyebrow">A clear next step</p><h2>Wherever you’re <em>starting.</em></h2></div><ol>{steps.map((step,i)=><li key={step.name}><span className="number">0{i+1}</span>{i<2&&<ArrowRight className="step-arrow" weight="thin"/>}<h3>{step.name}</h3><p>{step.copy}</p></li>)}</ol></section>
  <section className="final-cta"><div><p className="eyebrow">Ready when you are</p><h2>Not sure where to start?<br/><em>Start here.</em></h2><p>If you’re thinking about buying, selling, building, or investing, Nathanael can help you sort through the options and identify the right next step.</p></div><div className="actions"><a className="gold" href={agent.phoneHref}><Phone/> Call or Text Nathanael</a><a className="inline-link" href="#inquiry">Send a Message <ArrowRight/></a></div></section>
  <section id="inquiry" className="inquiry-section"><div><p className="eyebrow">Your next chapter</p><h2>Good things start<br/>with <em>a conversation.</em></h2><p>Buying your first home, planning a sale, or seeing potential in a property? Tell Nathanael what you have in mind.</p><a className="inline-link" href="/contact">Contact Nathanael directly <ArrowRight/></a></div><LeadForm source="Homepage"/></section>
 </>;
}