import {useEffect,useState} from 'react';
import {getProperties,isAvailableProperty} from './propertyApi';
import {PropertyCard} from './PropertyPages';
import {ArrowRight,ArrowUpRight,YoutubeLogo,Phone,MapPin,SealCheck,UsersThree,PhoneCall,HouseLine,ChartLineUp} from '@phosphor-icons/react';
import {agent,testimonials} from './data';
import {homeFaq} from './seo';
import {LeadForm} from './LeadForm';
const trust=[{Icon:SealCheck,text:'REALTOR® · DRE #02059393'},{Icon:MapPin,text:'Serving Kern County'},{Icon:ChartLineUp,text:'Real estate and investment'},{Icon:UsersThree,text:'Buyer, seller & investor guidance'},{Icon:PhoneCall,text:'Call or text direct'}];
const services=[{title:'Sell Your Home',href:'/real-estate',image:'property-front',alt:'A mountain home with a wraparound porch at sunset',w:1200,h:300,Icon:HouseLine,copy:'A thoughtful approach to timing, repairs, pricing, and next steps.',learn:'Learn about selling'},{title:'Buy a Home',href:'/properties',image:'house',alt:'Single-story home with a landscaped front yard',w:1200,h:300,Icon:HouseLine,copy:'Explore current listings and find a home that fits your goals.',learn:'Explore listings'},{title:'Investing',href:'/investing',image:'investing',alt:'City skyline with mountain views at sunset',w:1200,h:300,Icon:ChartLineUp,copy:'Talk through investment properties, flips, and opportunities with a practical eye.',learn:'Explore investing'}];
const reasons=[['01','Property perspective','A more informed eye for property condition, repairs, and potential.'],['02','Straightforward advice','Clear communication without pressure or unnecessary complexity.'],['03','Buyer, seller & investor support','A plan shaped around your budget, timeline, and reason for moving.'],['04','Local understanding','Grounded knowledge of Kern County and Tehachapi opportunities.']];
const areas=['Tehachapi','California City','Bakersfield','Stallion Springs'];
const steps=[{name:'Start with a conversation',copy:'Share your situation, questions, or property goals.'},{name:'Look at the details',copy:'Review the property, timing, numbers, and practical considerations.'},{name:'Decide on the right move',copy:'Create a plan that fits your goals, whether that means buying, selling, or waiting.'}];

export function Home({initialProperties=null}){
 const [listings,setListings]=useState(initialProperties?.filter(isAvailableProperty)||[]);
 const [loading,setLoading]=useState(initialProperties===null);
 const [wendyImageIdx,setWendyImageIdx]=useState(0);
 const wendyImages=['585-n-wendy-dr-newbury-park-ca.jpg','585-n-wendy-dr-newbury-park-ca-2.jpg','585-n-wendy-dr-newbury-park-ca-4.jpg','backyard.jpg','bathroom1.jpg','Diningroomfacingkitchen.jpg'];
 useEffect(()=>{let active=true;getProperties(initialProperties).then(list=>{if(active){setListings(list.filter(isAvailableProperty));setLoading(false)}});return()=>{active=false}},[]);
 useEffect(()=>{const timer=setInterval(()=>setWendyImageIdx(i=>(i+1)%wendyImages.length),7000);return()=>clearInterval(timer)},[]);
 return <>
  <section className="hero hero--standard" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">Real estate. Real experience.</p><h1 id="hero-title">It’s not what you do.<br/><em>It’s how you do it.</em></h1><div className="rule"/><p className="intro">Buy, sell, and invest in Kern County with Nathanael Harbison. Practical advice, thoughtful preparation, and a clear next step for your property goals.</p><div className="hero-actions"><a className="gold" href={agent.phoneHref}><Phone/> Call Nathanael</a><a className="text-link" href="/properties"><span>View Current Listings</span><ArrowRight/></a><a className="text-link text-link--small" href="#services"><span>Explore Services</span><ArrowRight/></a></div></div><aside className="location"><strong>Same<br/>mountains.<br/>Bigger<br/>opportunities.</strong><div className="rule"/><p>Tehachapi<br/>Kern County<br/>California</p></aside></section>
  <section className="page-wrap" style={{background:"white", padding:"2.5rem 2rem", borderBottom:"1px solid #f0f0f0"}}><article style={{maxWidth:"1200px", margin:"0 auto", display:"grid", gridTemplateColumns:"1fr 1fr", gap:"2rem", alignItems:"center"}}><div><p style={{fontSize:"0.85rem", color:"#806018", fontWeight:"600", margin:"0 0 0.5rem", textTransform:"uppercase"}}>Luxury Opportunity</p><h2 style={{fontSize:"2rem", margin:"0 0 1rem", lineHeight:"1.2"}}>585 N Wendy Dr<br/>Newbury Park</h2><p style={{fontSize:"1rem", color:"#555", margin:"0 0 1.5rem", lineHeight:"1.6"}}>Fully reimagined luxury residence with Boney Mountain views, chef’s kitchen, 400+ sq ft bonus room, and top-rated schools. Move-in ready.</p><div style={{display:"flex", gap:"1rem", margin:"0 0 1.5rem", flexWrap:"wrap"}}><span style={{background:"#f5f5f5", padding:"0.5rem 1rem", borderRadius:"4px", fontSize:"0.9rem"}}>3 beds</span><span style={{background:"#f5f5f5", padding:"0.5rem 1rem", borderRadius:"4px", fontSize:"0.9rem"}}>2 baths</span><span style={{background:"#f5f5f5", padding:"0.5rem 1rem", borderRadius:"4px", fontSize:"0.9rem"}}>1,633 sqft</span></div><a className="gold" href="/property/wendy" style={{display:"inline-block", padding:"0.85rem 2rem", background:"#d4af37", color:"#1a1a1a", borderRadius:"4px", textDecoration:"none", fontWeight:"bold", fontSize:"0.95rem"}}>Schedule Private Showing <ArrowRight style={{marginLeft:"0.5rem"}}/></a></div><div style={{borderRadius:"8px", aspectRatio:"1.4", overflow:"hidden", background:"#f0f0f0", position:"relative"}}><img src={`/assets/property/${wendyImages[wendyImageIdx]}`} alt="585 N Wendy Dr" style={{width:"100%", height:"100%", objectFit:"cover", transition:"opacity 0.5s", display:"block"}} loading="eager" decoding="async" width={1400} height={1000}/></div></article></section>
  <section className="trust-bar" aria-label="Credentials and service areas"><ul>{trust.map(({Icon,text})=><li key={text}><Icon weight="fill"/><span>{text}</span></li>)}</ul></section>
  <section className="home-about"><div><p className="eyebrow">More than a transaction</p><h2>A higher standard<br/>for <em>your next move.</em></h2></div><p>Whether you’re buying, selling, or exploring an investment, the right decision starts with understanding the property in front of you. Nathanael brings a practical perspective shaped by real estate work and a long-term view of value. <a className="inline-link" href="/about">Meet Nathanael <ArrowRight/></a><a className="inline-link" href={agent.youtube} target="_blank" rel="noreferrer"><YoutubeLogo/> Follow Nathanael on YouTube <ArrowUpRight/></a></p></section>
  <h2 className="sr-only" id="services-title">Sell your home, buy a home, or invest</h2><section id="services" className="services" aria-labelledby="services-title">{services.map(({title,href,image,alt,w,h,Icon,copy,learn})=><article key={title}><a className="service-card-link" href={href}><img className="service-photo" src={'/assets/'+image+'.webp'} alt={alt} width={w} height={h} loading="lazy" decoding="async"/><div className="service-body"><Icon weight="thin" className="service-icon"/><div><h3>{title}</h3><p>{copy}</p><span className="learn"><span>{learn}</span><ArrowRight/></span></div></div></a></article>)}</section>
  <section id="current-listings" className="portfolio-section page-wrap home-listings"><div className="section-heading"><div><p className="eyebrow">Available now</p><h2>Find your <em>next property.</em></h2></div><a className="inline-link" href="/properties">View all current listings <ArrowRight/></a></div><p className="listing-intro">Explore every current listing, with photos, price, and property details. Select a property to see more or ask about a showing.</p>{loading?<p role="status">Loading current listings…</p>:listings.length?<div className="property-grid">{listings.map(p=><PropertyCard key={p.slug||p.id} p={p} headingLevel={3}/>)}</div>:<p>New listings will appear here as they become available. <a className="inline-link" href="/contact">Tell Nathanael what you’re looking for <ArrowRight/></a></p>}</section>
  <section className="expertise-section page-wrap"><div className="section-heading"><div><p className="eyebrow">Why Harbison Standard</p><h2>Practical guidance.<br/><em>Direct communication. Real experience.</em></h2></div><p>How clients get more out of the process — not just the listing.</p></div><div className="expertise-grid">{reasons.map(([n,title,copy])=><article key={title}><span className="number">{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="testimonial-section"><div className="svc-head"><div><p className="eyebrow">Trusted along the way</p><h2>What clients <em>appreciate most.</em></h2></div></div><div className="testimonial-grid">{testimonials.map(t=><article className="testimonial-card" key={t.label}><blockquote><p>“{t.quote}”</p></blockquote><p className="t-label">{t.label}</p></article>)}</div></section>
  <section className="svc"><div className="svc-head"><div><p className="eyebrow">Areas served</p><h2>Serving clients across <em>Kern County.</em></h2></div><p>Including the communities below and the surrounding areas.</p></div><div className="areas">{areas.map(a=><span key={a}>{a}</span>)}</div></section>
  <section className="svc svc--tint"><div className="svc-head"><div><p className="eyebrow">Explore more</p><h2>Resources for <em>your search.</em></h2></div></div><div className="cards3">
   <article className="card-t"><h3>Why Tehachapi?</h3><p>Discover what makes this mountain community different — affordable land, four seasons, and a growing local economy.</p><a className="inline-link" href="/why-tehachapi">Learn about Tehachapi <ArrowRight/></a></article>
   <article className="card-t"><h3>Cheap land in Kern County</h3><p>View current land listings and learn what your budget buys in Bakersfield, Tehachapi, and the surrounding areas.</p><a className="inline-link" href="/cheap-land-kern-county">Explore land <ArrowRight/></a></article>
   <article className="card-t"><h3>Moving from LA?</h3><p>Compare what your budget buys in Bakersfield vs Los Angeles. Create a buyer profile for Kern County.</p><a className="inline-link" href="/moving-from-los-angeles-to-bakersfield">LA to Bakersfield <ArrowRight/></a></article>
  </div></section>
  <section className="svc svc--tint"><div className="svc-head"><div><p className="eyebrow">Common questions</p><h2>Quick answers,<br/><em>before you reach out.</em></h2></div><p>Straight answers to the questions buyers, sellers, and investors ask most.</p></div><div className="faq">{homeFaq.map(item=><details key={item.q}><summary>{item.q}</summary><p>{item.a}</p></details>)}</div></section>
  <section id="approach" className="process"><div><p className="eyebrow">A clear next step</p><h2>Wherever you’re <em>starting.</em></h2></div><ol>{steps.map((step,i)=><li key={step.name}><span className="number">0{i+1}</span>{i<2&&<ArrowRight className="step-arrow" weight="thin"/>}<h3>{step.name}</h3><p>{step.copy}</p></li>)}</ol></section>
  <section className="final-cta"><div><p className="eyebrow">Ready when you are</p><h2>Not sure where to start?<br/><em>Start here.</em></h2><p>If you’re thinking about buying, selling, or investing, Nathanael can help you sort through the options and identify the right next step.</p></div><div className="actions"><a className="gold" href={agent.phoneHref}><Phone/> Call or Text Nathanael</a><a className="inline-link" href="#inquiry">Send a Message <ArrowRight/></a></div></section>
  <section id="inquiry" className="inquiry-section"><div><p className="eyebrow">Your next chapter</p><h2>Good things start<br/>with <em>a conversation.</em></h2><p>Buying your first home, planning a sale, or seeing potential in a property? Tell Nathanael what you have in mind.</p><a className="inline-link" href="/contact">Contact Nathanael directly <ArrowRight/></a></div><LeadForm source="Homepage"/></section>
 </>;
}