import {useEffect,useState} from 'react';
import {ArrowRight,Check} from '@phosphor-icons/react';
import {BuyerIntentForm} from './BuyerIntentForm';
import {getProperties,isAvailableProperty} from './propertyApi';
import {money} from './data';
import {trackEvent} from './analytics';

export function MovingFromLosAngeles(){
 const [properties,setProperties]=useState([]);
 useEffect(()=>{getProperties().then(list=>setProperties((list||[]).filter(isAvailableProperty).filter(p=>!p.city||/bakersfield/i.test(p.city)).slice(0,3)))},[]);
 return <>
<section className="hero hero--standard relocation-hero"><div className="hero-copy"><p className="eyebrow">Los Angeles → Bakersfield</p><h1>See what your money buys <em>in Bakersfield.</em></h1><div className="rule"></div><p className="intro">More house. More land. A different market. Start with your actual budget and compare real options—not generic relocation claims.</p><div className="hero-actions"><a className="gold" href={properties.length?"#relocation-properties":"#relocation-form"}>{properties.length?"See available homes":"Find matching homes"} <ArrowRight/></a><a className="text-link" href="#relocation-form"><span>Tell us what you’re looking for</span><ArrowRight/></a></div></div></section>
<section className="svc"><div className="svc-head"><div><p className="eyebrow">Budget first</p><h2>What can the same budget <em>look like here?</em></h2></div><p>The useful comparison is not a slogan. It is the property type, square footage, land, condition, commute, renovation needs, and financing position that your budget can actually support.</p></div><div className="cards3">{[['$350K–$450K','Start with the attainable range','Use current inventory to see which neighborhoods, sizes, and condition levels are realistic.'],['$450K–$600K','Compare space and optionality','Look at larger homes, lot characteristics, condition, and how each home fits your priorities.'],['$600K+','Compare homes, land, and location','Evaluate higher-end resale, acreage, Tehachapi options, and how location and property condition affect your options.']].map(([n,t,c])=><article className="card-t" key={n}><span className="number">{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
{properties.length>0&&<section id="relocation-properties" className="portfolio-section page-wrap relocation-inventory"><div className="section-heading"><div><p className="eyebrow">Current inventory</p><h2>Start with <em>real properties.</em></h2></div><a className="inline-link" href="/properties">View all properties <ArrowRight/></a></div><div className="property-grid">{properties.map(p=><article className="property-card" key={p.slug||p.id}><a href={`/property/${p.slug||p.id}`} onClick={()=>trackEvent('property_select',{property_id:p.id,property_slug:p.slug,source:'la_relocation_page'})}><div className="property-image">{p.imageUrl?<img src={p.imageUrl} alt={`${p.address}, ${p.city}`} loading="lazy"/>:<div className="photo-unavailable">Property photo coming soon</div>}<span className="sold-badge">{p.status||'Available'}</span></div><div className="property-card-body"><div className="price-line"><strong>{p.price?money(p.price):'Contact for price'}</strong><span>{p.status||'Available'}</span></div><h2>{p.address||'Property opportunity'}</h2><p className="property-location">{[p.city,p.state,p.zip].filter(Boolean).join(' ')}</p></div></a></article>)}</div></section>}
<section className="svc svc--tint"><div className="svc-split"><div><p className="eyebrow">Relocation strategy</p><h2>The move is bigger than <em>the purchase.</em></h2><p>Price matters, but it does not answer the entire relocation question.</p></div><ul className="check-grid">{['Which Bakersfield or Kern County areas fit the lifestyle and property type you actually want','How much home or land your budget can realistically target','Whether you need to sell another property before, during, or after the move','How financing and timing affect negotiating position','Which homes deserve a closer closer look'].map(x=><li key={x}><Check weight="bold"/><span>{x}</span></li>)}</ul></div></section>
<section className="svc"><div className="svc-head"><div><p className="eyebrow">Use the buyer profile</p><h2>Don’t know the exact house yet?<br/><em>Define the target first.</em></h2></div><p>Tell us your budget, desired area, bedrooms, land requirements, timeline, financing status, and whether another property needs to sell. That creates a usable buyer profile instead of a generic contact request.</p></div></section>
<section id="relocation-form" className="inquiry-section"><div><p className="eyebrow">Los Angeles buyer profile</p><h2>Give us the target.<br/><em>We’ll narrow the field.</em></h2><p>Share your goals once so Nathanael can follow up with relevant properties and practical next steps.</p></div><BuyerIntentForm source="la-to-bakersfield"/></section>
</>}
