// New listings collected 2026-09-19
// Each listing has complete info from public syndicated sources with attribution.
// "Listing courtesy of..." credit remains with the original listing agent/brokerage.
export const newListings = [
  {
    id: '21204-stage-dr',
    slug: '21204-stage-dr',
    address: '21204 Stage Dr',
    city: 'Tehachapi',
    zip: '93561',
    region: 'Kern County',
    price: 499900,
    beds: 4,
    baths: 2,
    sqft: 1945,
    lot: '0.48 acres',
    date: '2026-08-21',
    yearBuilt: 2026,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Descygene Simunovich, Miramar Intl Tehachapi.',
    sourceMls: '9994415',
    description: 'Brand New Construction in West Golden Hills! This beautiful 4 bedroom, 2 bath home offers approximately 1,945 sq. ft. on a spacious .48 acre lot. The desirable split-wing floor plan features luxury vinyl plank flooring, a stylish kitchen with soft-close cabinetry and a walk-in pantry, plus a spacious interior laundry room. The primary suite includes a beautifully tiled shower and two walk-in closets. Additional highlights include an oversized attached 2 car garage, Presidential style composition roof, and paid off solar. Enjoy the comfort and efficiency of a brand new home in the desirable West Golden Hills area of Tehachapi, where deer are often seen passing through the area.',
    context: 'Brand new construction in West Golden Hills — 4 bed, 2 bath, 1,945 sq ft on .48 acres with paid solar, oversized 2-car garage, and Presidential composition roof.',
    features: ['New construction 2026', 'Split-wing floor plan', 'Luxury vinyl plank flooring', 'Soft-close cabinetry', 'Walk-in pantry', 'Oversized 2-car garage', 'Paid-off solar', 'Presidential composition roof', 'R-1 zoning'],
    imageUrl: '/assets/property/21204-stage-dr-1.jpg',
    images: Array.from({length: 24}, (_, i) => `/assets/property/21204-stage-dr-${i + 1}.jpg`),
    locationContext: 'West Golden Hills area of Tehachapi — a desirable location known for mountain views, deer passing through, and proximity to local amenities.',
  },
  {
    id: '18211-sulky-ln',
    slug: '18211-sulky-ln',
    address: '18211 Sulky Ln',
    city: 'Tehachapi',
    zip: '93561',
    region: 'Kern County',
    price: 499000,
    beds: 3,
    baths: 3,
    sqft: 2496,
    lot: '0.27 acres',
    date: '2026-09-14',
    yearBuilt: 2018,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Heather McKinley, Keller Williams Tehachapi.',
    sourceMls: '9994314',
    description: 'Luxury, convenience, and low-maintenance living come together in this beautifully crafted Stallion Springs home, modern, spacious, and ideally located — mountain living without the maintenance. Built in 2018, this beautifully designed residence offers 3 bedrooms, 3 bathrooms, and nearly 2,500 square feet of thoughtfully planned living space. Soaring ceilings, abundant natural light, and an open-concept floor plan create an inviting atmosphere for both everyday living and entertaining. The spacious great room flows seamlessly into the stunning chef\'s kitchen, complete with beautiful cabinetry, generous prep space, a large center island, and modern finishes. The expansive primary suite provides a peaceful retreat with a spa-inspired ensuite bathroom, dual vanities, a walk-in shower, and a generous walk-in closet. Perfectly situated in one of the community\'s most convenient locations — just a short walk to local restaurants, Stallion Springs Community Center, swimming pool, parks, and neighborhood amenities.',
    context: 'Modern Stallion Springs residence — 3 bed, 3 bath, nearly 2,500 sq ft with soaring ceilings, chef\'s kitchen, and spa-inspired primary suite.',
    features: ['Built 2018', 'Open-concept floor plan', 'Chef\'s kitchen with center island', 'Spa-inspired primary suite', 'Dual vanities', 'Walk-in shower', 'Low-maintenance landscaping', 'Walking distance to community amenities'],
    imageUrl: '/assets/property/18211-sulky-ln-1.jpg',
    images: Array.from({length: 45}, (_, i) => `/assets/property/18211-sulky-ln-${i + 1}.jpg`),
    locationContext: 'Stallion Springs — one of Tehachapi\'s most desirable mountain communities with year-round recreation and a true sense of community.',
  },
  {
    id: '28211-seabiscuit-way',
    slug: '28211-seabiscuit-way',
    address: '28211 Seabiscuit Way',
    city: 'Tehachapi',
    zip: '93561',
    region: 'Kern County',
    price: 699000,
    beds: 4,
    baths: 3,
    sqft: 2836,
    lot: '0.75 acres',
    date: '2026-08-29',
    yearBuilt: 2010,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Adonae Faris, Tehachapi Summit Real Estate.',
    sourceMls: '9994413',
    description: 'Welcome to this exceptional Stallion Springs home offering space, privacy, thoughtful design, and freedom. With approximately 2,836 square feet, 4 bedrooms, 3 bathrooms, and a spacious 3 car garage, this beautifully appointed residence offers the perfect blend of mountain living and modern comfort. A welcoming entry opens to generous dining space and den, and a split-wing floor plan provides privacy and flexibility for family and guests. The expansive primary suite is a true retreat, featuring vaulted ceilings, walk-in closet and separate 2nd closet, a luxurious soaking tub, and large walk-in shower. At the heart of the home, the kitchen features granite countertops, abundant cabinetry, a pantry, breakfast nook, and freshly painted cabinets. The home also has a tankless water heater, central vacuum, and fully paid-off solar system with panels and battery storage. Outside you\'ll find a beautiful patio featuring a fire pit and waterfall, perfect for entertaining, relaxing, and enjoying Tehachapi\'s spectacular four-season climate.',
    context: 'Spacious Stallion Springs home — 4 bed, 3 bath, 2,836 sq ft on .75 acres with paid solar + battery, 3-car garage, and outdoor fire pit and waterfall.',
    features: ['Built 2010', 'Split-wing floor plan', 'Vaulted ceilings in primary suite', 'Soaking tub & walk-in shower', 'Tankless water heater', 'Paid-off solar + battery storage', 'Central vacuum', 'EV charger outlet', 'Water softener', 'RV gate & hookups', 'Outdoor fire pit & waterfall'],
    imageUrl: '/assets/property/28211-seabiscuit-way-1.jpg',
    images: Array.from({length: 36}, (_, i) => `/assets/property/28211-seabiscuit-way-${i + 1}.jpg`),
    locationContext: 'Stallion Springs — sweeping mountain views and a serene setting with convenient access to all Tehachapi has to offer.',
  },
  {
    id: '28751-gleneagle-ct',
    slug: '28751-gleneagle-ct',
    address: '28751 Gleneagle Ct',
    city: 'Tehachapi',
    zip: '93561',
    region: 'Kern County',
    price: 499999,
    beds: 3,
    baths: 2.5,
    sqft: 2364,
    lot: '0.47 acres',
    date: '2026-09-12',
    yearBuilt: 2004,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Chrystle Deal & Monique Weese, LRS Realty & Management, Inc.',
    sourceMls: '202603588',
    description: 'Welcome to 28751 Gleneagle Ct, an exceptional Stallion Springs residence offering sweeping mountain views and refined living in a serene setting. This thoughtfully designed home features 3 bedrooms, 2.5 bathrooms, and a versatile bonus room ideal for an office, gym, or guest retreat. The primary suite offers private deck access, a walk-in closet, and picturesque views. The great room is highlighted by dramatic floor-to-ceiling windows that fill the home with natural light. The kitchen features granite countertops, stainless steel appliances, ample cabinetry, and flows into formal and casual dining areas. Additional highlights include an oversized 3-car garage, expansive deck, and greenhouse.',
    context: 'Stallion Springs mountain home — 3 bed, 2.5 bath, 2,364 sq ft with floor-to-ceiling windows, sweeping views, oversized 3-car garage, and greenhouse.',
    features: ['Built 2004', 'Floor-to-ceiling windows', 'Mountain views', 'Primary suite with private deck', 'Bonus room', 'Granite countertops', 'Stainless steel appliances', 'Oversized 3-car garage', 'Expansive deck', 'Greenhouse'],
    imageUrl: '/assets/property/28751-gleneagle-ct-1.jpg',
    images: Array.from({length: 45}, (_, i) => `/assets/property/28751-gleneagle-ct-${i + 1}.jpg`),
    locationContext: 'Stallion Springs — serene mountain setting with convenient access to trails, golf, and community amenities.',
  },
  {
    id: '958-fairway-dr',
    slug: '958-fairway-dr',
    address: '958 Fairway Dr',
    city: 'Bakersfield',
    zip: '93309',
    region: 'Kern County',
    price: 899900,
    beds: 4,
    baths: 3,
    sqft: 2170,
    lot: '10,744 sq ft',
    date: '2026-08-21',
    yearBuilt: 1961,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Cecilia Clark, Emerge Real Estate.',
    sourceMls: 'OC26184352',
    description: 'Welcome to this beautifully renovated 4-bedroom, 3-bathroom home nestled in the prestigious Stockdale Country Club. From the moment you arrive, the quality and care put into this home are unmistakable. A brand new Presidential roof, updated 200-amp electrical panel, and renovated pool mean the big ticket items are already taken care of, giving you confidence and peace of mind from day one. Inside, the fully renovated interior delivers a fresh, modern feel throughout, complemented by a desirable dual en-suite layout offering two private bedroom and bathroom combinations, perfect for multigenerational living or hosting guests in style. Outside, the renovated pool and dedicated outdoor dining area create a backyard setting built for entertaining and everyday enjoyment.',
    context: 'Fully renovated Stockdale Country Club gem — 4 bed, 3 bath with dual en-suites, renovated pool, new Presidential roof, and 200-amp panel.',
    features: ['Stockdale Country Club location', 'Dual en-suite layout', 'Renovated pool', 'New Presidential roof', '200-amp electrical panel', 'Outdoor dining area', 'Fully renovated interior', 'Two private bedroom suites'],
    imageUrl: '/assets/property/958-fairway-dr-1.jpg',
    images: Array.from({length: 66}, (_, i) => `/assets/property/958-fairway-dr-${i + 1}.jpg`),
    locationContext: 'Stockdale Country Club — one of Bakersfield\'s most prestigious neighborhoods with sought-after location and mature landscaping.',
  },
  {
    id: '2300-weybridge-dr',
    slug: '2300-weybridge-dr',
    address: '2300 Weybridge Dr',
    city: 'Bakersfield',
    zip: '93311',
    region: 'Kern County',
    price: 2895000,
    beds: 5,
    baths: 8,
    sqft: 7025,
    lot: '19,602 sq ft',
    date: '2026-07-15',
    yearBuilt: 1994,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of William Gordon, Watson Realty.',
    sourceMls: 'V137657',
    description: 'Stunning 7,000+ sq ft estate with $1,000,000+ remodel! Situated on the 9th hole of the Islands course, you are only a short walk from the Seven Oaks clubhouse. One of the most striking features is the refinished wood flooring, cabinetry, coffered ceilings and banisters, particularly in the study, foyer and staircase. Equally beautiful is the extensive use of alabaster colored Dolomite marble slab and tile. The gourmet kitchen has high-end Wolf appliances and premier custom cabinets. Several gorgeous crystal chandeliers accentuate the space. The owner\'s suite is located on the ground floor with its 3 walk-in closets plus sitting area and direct access to the back yard spa. 4 ensuite bedrooms upstairs, all with walk-in closets. Floor plan features elegant formal living and dining rooms, a family room open to the kitchen with golf course views, office, and a loft living area upstairs. Finished walk-out basement used as gym/storage. Owned solar system and elevator with access to all three floors.',
    context: 'Magnificent Seven Oaks estate — 5 bed, 8 bath, 7,025+ sq ft with $1M+ remodel, golf course views, elevator, owned solar, and gourmet Wolf kitchen.',
    features: ['Seven Oaks gated community', 'Islands golf course views', 'Owner on main floor', '4 ensuite bedrooms upstairs', 'Walk-out basement', 'Elevator to all 3 floors', 'Owned solar system', 'High-end Wolf appliances', 'Crystal chandeliers', 'Dolomite marble slab & tile', 'Coffered ceilings', '3 walk-in closets in primary'],
    imageUrl: '/assets/property/2300-weybridge-dr-1.jpg',
    images: Array.from({length: 76}, (_, i) => `/assets/property/2300-weybridge-dr-${i + 1}.jpg`),
    locationContext: 'Seven Oaks — one of Bakersfield\'s most prestigious gated communities with championship golf, clubhouse, and resort-style amenities.',
  },
  {
    id: '2206-ribble-valley-dr',
    slug: '2206-ribble-valley-dr',
    address: '2206 Ribble Valley Dr',
    city: 'Bakersfield',
    zip: '93311',
    region: 'Kern County',
    price: 975000,
    beds: 5,
    baths: 3,
    sqft: 3123,
    lot: '14,375 sq ft',
    date: '2026-08-26',
    yearBuilt: 2006,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Jeff Jackson, Cal Connect Realty Group Inc.',
    sourceMls: 'NS26187383',
    description: 'Prestigious Gibbons & Wheelan home located in the gated Grand Island community at Seven Oaks. An elegant tiered stone-entry staircase, stacked-stone pillars, manicured landscaping, exposed rafter-tail eaves, and a rock-accented elevation create exceptional curb appeal. Custom double wrought-iron entry doors with hand-forged scrollwork welcome you inside, where you\'ll find tray ceilings, custom 20-inch tile flooring, and a desirable three-way split-wing design. The granite kitchen features upscale custom cabinetry, a center island, a wine refrigerator, and a custom backsplash. Offering five spacious bedrooms and three bathrooms, including a Jack-and-Jill bathroom, this home is designed for both comfort and functionality. The owner\'s suite features tray ceilings, modern paint accents, abundant natural light, and a must-see walk-in closet. Outside, enjoy park-like grounds, mature landscaping, a waterfall pool, and a large covered patio — ideal for entertaining.',
    context: 'Grand Island gated estate — 5 bed, 3 bath, 3,123 sq ft in Seven Oaks with waterfall pool, tray ceilings, and custom wrought-iron entry doors.',
    features: ['Grand Island gated community', 'Seven Oaks location', 'Custom wrought-iron entry doors', 'Tray ceilings', 'Split-wing design', 'Granite kitchen with center island', 'Wine refrigerator', 'Waterfall pool', 'Covered patio', 'Walk-in closet in primary'],
    imageUrl: '/assets/property/2206-ribble-valley-dr-1.jpg',
    images: Array.from({length: 66}, (_, i) => `/assets/property/2206-ribble-valley-dr-${i + 1}.jpg`),
    locationContext: 'Seven Oaks Grand Island — exclusive gated enclave within one of Bakersfield\'s most prestigious master-planned communities.',
  },
  {
    id: '2901-summit-cir',
    slug: '2901-summit-cir',
    address: '2901 Summit Cir',
    city: 'Bakersfield',
    zip: '93306',
    region: 'Kern County',
    price: 359000,
    beds: 2,
    baths: 1.75,
    sqft: 2209,
    lot: '6,570 sq ft',
    date: '2026-07-18',
    yearBuilt: 1961,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Bradley Barnett, Century 21 Select Real Estate.',
    sourceMls: '202607788',
    description: 'Owned Solar. No Lease, No Loan! Discover easy, resort-like living in the unmatched Summit Villas, a gated 55+ community of only 12 custom homes. Residents enjoy a private clubhouse, sparkling pool, and a reservable guest house while the HOA maintains the community\'s shared amenities. This beautiful home offers approximately 2,209 square feet with abundant flexible-use spaces designed for comfortable living. Wide hallways, motion-activated lighting, and a step-in shower in the primary suite provide convenience while supporting long-term accessibility. The oversized primary suite offers exceptional closet space and a peaceful retreat, while the expansive covered patio creates an ideal setting for relaxing or hosting friends. Located within walking distance to the Panorama Bluffs walking trails and the Levan Institute for Lifelong Learning.',
    context: 'Gated 55+ Summit Villas community — 2 bed, 1.75 bath, 2,209 sq ft with owned solar, private clubhouse, pool, and access to guest house.',
    features: ['55+ gated community', 'Only 12 custom homes', 'Owned solar — no lease/loan', 'Private clubhouse', 'Community pool', 'Reservable guest house', 'Wide hallways', 'Motion-activated lighting', 'Step-in shower', 'Covered patio'],
    imageUrl: '/assets/property/2901-summit-cir-1.jpg',
    images: Array.from({length: 51}, (_, i) => `/assets/property/2901-summit-cir-${i + 1}.jpg`),
    locationContext: 'Summit Villas — exclusive gated 55+ community near Panorama Bluffs walking trails and the Levan Institute for Lifelong Learning.',
  },
  {
    id: '3109-mount-vernon-ave',
    slug: '3109-mount-vernon-ave',
    address: '3109 Mount Vernon Ave',
    city: 'Bakersfield',
    zip: '93306',
    region: 'Kern County',
    price: 299900,
    beds: 4,
    baths: 2,
    sqft: 1680,
    lot: '8,276 sq ft',
    date: '2026-09-18',
    yearBuilt: 1957,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Jorge Solis, Infinity Real Estate Services.',
    sourceMls: '202607149',
    description: 'Home features a dining room, breakfast area, large family room, laundry room, 1,680 sq ft of living space, Central Heat & Air, Alley Access, 4 bedrooms, 2 bathrooms, Spacious backyard 8,276 sq ft lot size plus a mother-in-law unit with its own kitchenette. All showings are subject to an interior inspection. The property is being sold with the tenant in place. The current long-term tenant pays $1,800 per month and is under a lease through October 31, 2026. No FHA financing; conventional or cash offers only.',
    context: 'East Bakersfield investment opportunity — 4 bed, 2 bath, 1,680 sq ft with mother-in-law unit, tenant in place at $1,800/mo through Oct 2026.',
    features: ['Mother-in-law unit with kitchenette', 'Tenant in place — $1,800/mo', 'Lease through October 31, 2026', 'Central Heat & Air', 'Alley access', 'Conventional or cash only'],
    imageUrl: '/assets/property/3109-mount-vernon-ave-1.jpg',
    images: Array.from({length: 29}, (_, i) => `/assets/property/3109-mount-vernon-ave-${i + 1}.jpg`),
    locationContext: 'East Bakersfield — established neighborhood with convenient access to local amenities.',
  },
  {
    id: '909-oberlin-ct',
    slug: '909-oberlin-ct',
    address: '909 Oberlin Ct',
    city: 'Bakersfield',
    zip: '93305',
    region: 'Kern County',
    price: 299900,
    beds: 3,
    baths: 2,
    sqft: 1350,
    lot: '10,000 sq ft',
    date: '2026-09-18',
    yearBuilt: 1954,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Jesus H Garcia, The Mora Partners Inc.',
    sourceMls: '202608755',
    description: 'Welcome to this beautifully updated 3-bedroom, 2-bathroom home situated on a quiet cul-de-sac and set on an expansive 10,000-square-foot lot! Step inside to an inviting living area featuring recessed lighting, ceiling fans, and large windows that provide abundant natural light. The updated kitchen offers quartz countertops, a new sink, and modern lighting, creating a stylish and functional space for everyday living and entertaining. Both bathrooms have been tastefully upgraded with new vanities, flooring, mirrors, and showers. Additional improvements include a new roof, solar panels, new electrical panel, wood fencing, recessed lighting, ceiling fans, and convenient indoor laundry. Outside, the home has been freshly painted and features a detached storage shop in the backyard, providing additional space for storage, hobbies, or projects. The huge lot offers plenty of possibilities, including the potential to add a pool or ADU.',
    context: 'Updated East Bakersfield home on cul-de-sac — 3 bed, 2 bath, 1,350 sq ft with new roof, solar, quartz counters, and potential for ADU or pool.',
    features: ['Quiet cul-de-sac location', 'Updated kitchen with quartz countertops', 'New roof & solar panels', 'New electrical panel', 'Recessed lighting & ceiling fans', 'Indoor laundry', 'Detached storage shop', 'Freshly painted interior & exterior', 'ADU potential (buyer to verify)'],
    imageUrl: '/assets/property/909-oberlin-ct-1.jpg',
    images: Array.from({length: 34}, (_, i) => `/assets/property/909-oberlin-ct-${i + 1}.jpg`),
    locationContext: 'East Bakersfield — quiet cul-de-sac location near shopping, schools, and freeway access.',
  },
  {
    id: '505-jeffrey-st',
    slug: '505-jeffrey-st',
    address: '505 Jeffrey St',
    city: 'Bakersfield',
    zip: '93305',
    region: 'Kern County',
    price: 287000,
    beds: 2,
    baths: 2,
    sqft: 0,
    lot: '6,969 sq ft',
    date: '2026-09-18',
    yearBuilt: 1922,
    propertyType: 'Single Family',
    status: 'Available',
    attribution: 'Listing courtesy of Karmen Domani, Real Broker.',
    sourceMls: '202608357',
    description: 'Beautifully remodeled 2-bedroom, 2-bath home on an oversized lot in East Bakersfield. This move-in ready property has been extensively updated, including new plumbing and electrical, a new kitchen with updated cabinetry, countertops and fixtures, fully renovated bathrooms, new flooring, fresh interior and exterior paint, and updated lighting. The bright, functional floor plan maximizes the living space and offers a clean, modern feel throughout. The large lot provides exceptional outdoor space with room for entertaining, future improvements or potential ADU possibilities (buyer to verify). With extensive updates already completed, this property offers an excellent opportunity for an owner-occupant or investor looking for a turnkey, low-maintenance home.',
    context: 'Turnkey remodeled East Bakersfield — 2 bed, 2 bath with new plumbing, electrical, kitchen, baths, flooring, and potential for ADU.',
    features: ['New plumbing & electrical', 'New kitchen with updated cabinetry', 'Fully renovated bathrooms', 'New flooring throughout', 'Fresh interior & exterior paint', 'Updated lighting', 'Oversized lot', 'ADU potential (buyer to verify)', 'Turnkey condition'],
    imageUrl: '/assets/property/505-jeffrey-st-1.jpg',
    images: Array.from({length: 18}, (_, i) => `/assets/property/505-jeffrey-st-${i + 1}.jpg`),
    locationContext: 'East Bakersfield — convenient location near shopping, schools, and freeway access.',
  },
];
