import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Phone,Envelope,MapPin,HouseLine,YoutubeLogo} from '@phosphor-icons/react';
import {agent,properties,money,soldDate} from './data';
import {LeadForm} from './LeadForm';
import {SocialLinks} from './SocialLinks';
export function About(){return <>
 <section className="about-hero page-wrap"><div><p className="eyebrow">Meet Nathanael Harbison</p><h1>Experience built<br/>from <em>the ground up.</em></h1><p className="page-lede">A builder’s eye. A neighbor’s perspective.<br/>A higher standard for your next move.</p><a className="gold" href="/contact">Work with Nate <ArrowRight/></a><p className="credentials">REALTOR® · Harbison Standard · DRE #{agent.license}</p></div><figure className="portrait"><img src="/assets/headshot.webp" alt="Nathanael Harbison smiling"/><figcaption><span>Nathanael Harbison</span><small>Real estate. Real experience.</small></figcaption></figure></section>
 <section className="bio-section page-wrap"><div><p className="eyebrow">The person behind the standard</p><h2>Practical knowledge.<br/><em>Personal commitment.</em></h2></div><div className="bio-copy"><p>Nathanael began building homes in 2017. Today, he brings that construction background to buyers, sellers, and investors across Kern County and San Diego.</p><p>Earlier work in the oil fields shaped his work ethic; time in the service industry shaped his approach to people. His real estate practice centers on empathy, integrity, and accountability.</p><p>Outside real estate, his interests include obstacle races, community movie nights, and local volunteering.</p><a className="inline-link" href={agent.youtube} target="_blank" rel="noreferrer"><YoutubeLogo/> Follow Nate’s builds on YouTube <ArrowUpRight/></a></div></section>
 <section className="expertise-section page-wrap"><div className="section-heading"><div><p className="eyebrow">How Nate can help</p><h2>Your goals.<br/><em>His experience.</em></h2></div><p>Start with what matters to you.<br/>Build a clear plan for what comes next.</p></div><div className="expertise-grid">{[
 ['01','Buying & selling','From a first home to a fresh start, get guidance through the decisions that come with a move.','Buying'],
 ['02','New construction','Bring a builder’s perspective to your new-home search and conversations about a property’s potential.','Building or renovating'],
 ['03','Investment properties','Talk through your property goals, including investment purchases and 1031 exchanges.','Investing'],
 ['04','Relocation','Plan a move with support for relocation, including military buyers and veterans.','Buying'],
 ].map(([n,title,copy,goal])=><article key={title}><span className="number">{n}</span><h3>{title}</h3><p>{copy}</p><a className="inline-link" href={'/contact?goal='+encodeURIComponent(goal)}>Let’s talk <ArrowRight/></a></article>)}</div></section>
 <section className="community-band page-wrap"><p className="eyebrow">Rooted in community</p><h2>More than a place to live.<br/><em>A place to belong.</em></h2><p>Nate supports the Tehachapi community through movie nights, the local Alano club, Cornerstone Life Development, and the Tehachapi Mud Run.</p><a className="gold" href="/contact">Get to know Nate <ArrowRight/></a></section>
 </>}
function PropertyPhoto({property,featured=false}){const [failed,setFailed]=useState(false);return <div className="property-image">{failed?<div className="photo-unavailable"><HouseLine/><span>Photo available on the original listing</span></div>:<img src={'/assets/sold/'+property.id+'.webp'} alt={property.address+', '+property.city} loading={featured?'eager':'lazy'} onError={()=>setFailed(true)}/>}<span className="sold-badge">Sold</span></div>}
function PropertyFacts({property:p}){return <div className="property-facts"><span>{p.beds} beds</span><span>{p.baths} baths</span><span>{p.sqft.toLocaleString('en-US')} sq ft</span></div>}
export function Properties(){const [region,setRegion]=useState('All locations');const featured=properties[0];const shown=properties.filter(p=>region==='All locations'?p.id!==featured.id:p.region===region);return <>
 <section className="page-heading page-wrap"><p className="eyebrow">The property portfolio</p><h1>Real places.<br/><em>Real results.</em></h1><p className="page-lede">A selection of Nate’s past transactions.<br/>From mountain retreats to the next chapter in the city.</p></section>
 {region==='All locations'&&<section className="featured-property page-wrap" aria-label="Featured past sale"><PropertyPhoto property={featured} featured/><div className="featured-copy"><p className="eyebrow">Featured past sale · Tehachapi</p><p className="featured-price">{money(featured.price)}</p><h2>{featured.address}</h2><p className="property-location">{featured.city}, CA {featured.zip}</p><PropertyFacts property={featured}/><p className="property-description">{featured.description}</p><p className="sale-date">Sold {soldDate(featured.date)} · {featured.lot}</p></div></section>}
 <section className="portfolio-section page-wrap"><div className="portfolio-controls"><div><p className="eyebrow">Past sales</p><p role="status">{region==='All locations'?properties.length:shown.length} properties{region==='All locations'?' including featured sale':''}</p></div><div className="property-filters" role="group" aria-label="Filter properties by location">{['All locations','Kern County','San Diego County'].map(r=><button key={r} aria-pressed={r===region} onClick={()=>setRegion(r)}>{r}</button>)}</div></div><div className="property-grid">{shown.map(p=><article className="property-card" key={p.id}><PropertyPhoto property={p}/><div className="property-card-body"><div className="price-line"><strong>{money(p.price)}</strong><span>{soldDate(p.date)}</span></div><h2>{p.address}</h2><p className="property-location">{p.city}, CA {p.zip}</p><PropertyFacts property={p}/></div></article>)}</div><p className="source-note">Past transactions and listing photos are shared for reference. These homes have sold and are not currently offered here. Details checked September 6, 2026. Measurements are approximate.</p></section>
 <section className="property-cta page-wrap"><div><p className="eyebrow">What comes next?</p><h2>Let’s find <em>your opportunity.</em></h2><p>Looking to buy, sell, or explore a property’s potential?</p></div><a className="gold" href="/contact?goal=Buying">Start a conversation <ArrowRight/></a></section>
 </>}
export function Contact(){return <section className="contact-page page-wrap"><div className="contact-copy"><p className="eyebrow">Let’s talk</p><h1>Your next move<br/>starts <em>here.</em></h1><p className="page-lede">A question, a plan, or just a possibility.<br/>Nate would like to hear it.</p><div className="contact-person"><img src="/assets/headshot.webp" alt="Nathanael Harbison"/><div><h2>{agent.name}</h2><p>REALTOR® · Harbison Standard</p><small>DRE #{agent.license}</small></div></div><div className="contact-methods"><a href={agent.phoneHref}><Phone/><span><small>Call Nate</small>{agent.phone}</span><ArrowUpRight/></a><a href={'mailto:'+agent.email}><Envelope/><span><small>Email Nate</small>{agent.email}</span><ArrowUpRight/></a><div><MapPin/><span><small>Areas served</small>Kern County & San Diego, California</span></div></div><p className="eyebrow follow-label">Follow along</p><SocialLinks showLabels/></div><div id="inquiry"><LeadForm source="Contact page"/></div></section>}
