import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Phone,Envelope,MapPin,HouseLine,YoutubeLogo,Check,ChatCircleText} from '@phosphor-icons/react';
import {agent,properties,money,soldDate,testimonials} from './data';
import {LeadForm} from './LeadForm';
import {QuickForm} from './QuickForm';
import {SocialLinks} from './SocialLinks';
import {contactFaq} from './seo';

export function About(){return <>
 <section className="about-hero page-wrap"><div><p className="eyebrow">Meet Nathanael Harbison</p><h1>Experience built<br/>from <em>the ground up.</em></h1><p className="page-lede">Nathanael Harbison brings together real estate experience, construction knowledge, and a people-first approach to help clients make more confident decisions.</p><a className="gold" href="/contact">Work With Nathanael <ArrowRight/></a><p className="credentials">REALTOR® · Harbison Standard · DRE #{agent.license}</p></div><figure className="portrait"><img src="/assets/headshot.webp" alt="Nathanael Harbison smiling"/><figcaption><span>Nathanael Harbison</span><small>Real estate. Real experience.</small></figcaption></figure></section>
 <section className="bio-section page-wrap"><div><p className="eyebrow">Meet Nathanael Harbison</p><h2>A people-first approach.<br/><em>Practical experience.</em></h2></div><div className="bio-copy"><p>Before real estate, Nathanael worked in the oil fields and in service-based roles that shaped how he approaches responsibility, pressure, and people. In 2017, he began building homes, gaining firsthand experience that now helps him guide buyers, sellers, and investors with a more practical perspective.</p><p>Today, he serves clients across Kern County with an approach centered on honesty, clarity, and long-term value.</p><a className="inline-link" href={agent.youtube} target="_blank" rel="noreferrer"><YoutubeLogo/> Follow Nathanael’s builds on YouTube <ArrowUpRight/></a></div></section>
 <section className="expertise-section page-wrap"><div className="section-heading"><div><p className="eyebrow">Why this experience matters</p><h2>Why it matters <em>for you.</em></h2></div><p>Construction experience changes the conversations clients can have about property.</p></div><div className="expertise-grid">{[
  ['01','A better eye for property condition','Helpful when evaluating repairs, quality, and potential concerns.'],
  ['02','More practical conversations','Especially around renovations, land, and value-add opportunities.'],
  ['03','Clearer expectations','A grounded perspective on what a property may require.'],
  ['04','Less guesswork','Helpful guidance for clients who want to understand more than just the listing.'],
  ].map(([n,title,copy])=><article key={title}><span className="number">{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="svc"><div className="svc-head"><div><p className="eyebrow">Career timeline</p><h2>The path behind <em>the work.</em></h2></div><p>Each step shaped how Nathanael works with people and property.</p></div><ol className="timeline">{[['Service industry background','Built communication and people skills'],['Oil field work','Developed work ethic and accountability'],['Home building · 2017','Hands-on construction experience'],['Real estate practice','Helping buyers, sellers, and investors make better-informed decisions']].map(([name,copy])=><li key={name}><div><strong>{name}</strong><p>{copy}</p></div></li>)}</ol></section>
 <section className="svc svc--tint"><div className="svc-split"><div><p className="eyebrow">How Nathanael works</p><h2>What it’s like to <em>work with Nathanael.</em></h2><p className="svc-body">People hire a working style as much as credentials. This is the way Nathanael approaches every client relationship.</p></div><ul className="check-grid">{['Straightforward and responsive','Practical, not pushy','Thoughtful under pressure','Attentive to detail','Focused on long-term fit, not just the quickest close'].map(item=><li key={item}><Check weight="bold"/><span>{item}</span></li>)}</ul></div></section>
 <section className="svc"><div className="svc-head"><div><p className="eyebrow">Ways Nathanael helps</p><h2>Where his experience is <em>most valuable.</em></h2></div></div><div className="cards4">{[
  ['Buying & Selling','Guidance through the process with clear next steps.'],
  ['New Construction','A practical perspective on lots, spec homes, and building plans.'],
  ['Investment Properties','Help evaluating opportunities with a long-term lens.'],
  ['Relocation & Life Changes','Support through transitions that involve more than just the transaction.'],
  ].map(([title,copy])=><article className="card-t" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="community-band page-wrap"><p className="eyebrow">Rooted in the community</p><h2>More than a place to live.<br/><em>A place to belong.</em></h2><p>Nathanael’s work is shaped by involvement in the community he serves. Local events, volunteering, and neighborhood relationships reinforce a simple belief: real estate is about people, not just property.</p><ul className="community-list"><li>Tehachapi community movie nights</li><li>The local Alano club</li><li>Cornerstone Life Development</li><li>The Tehachapi Mud Run</li></ul><a className="gold" href="/contact">Get to know Nathanael <ArrowRight/></a></section>
 <section className="testimonial-section"><div className="svc-head"><div><p className="eyebrow">Client feedback</p><h2>What clients say about <em>working with Nathanael.</em></h2></div></div><div className="testimonial-grid">{testimonials.map(t=><article className="testimonial-card" key={t.label}><blockquote><p>“{t.quote}”</p></blockquote><p className="t-label">{t.label}</p></article>)}</div></section>
 <section className="final-cta"><div><p className="eyebrow">Your next step</p><h2>Looking for practical guidance<br/>and a <em>clear next step?</em></h2></div><div className="actions"><a className="gold" href={agent.phoneHref}><Phone/> Call Nathanael</a><a className="inline-link" href="/contact">Send a Message <ArrowRight/></a></div></section>
 </>}

function PropertyPhoto({property,featured=false}){const [failed,setFailed]=useState(false);return <div className="property-image">{failed?<div className="photo-unavailable"><HouseLine/><span>Photo available on the original listing</span></div>:<img src={'/assets/sold/'+property.id+'.webp'} alt={property.address+', '+property.city} loading={featured?'eager':'lazy'} onError={()=>setFailed(true)}/>}<span className="sold-badge">Sold</span></div>}
function PropertyFacts({property:p}){return <div className="property-facts"><span>{p.beds} beds</span><span>{p.baths} baths</span><span>{p.sqft.toLocaleString('en-US')} sq ft</span></div>}

export function Properties(){const [region,setRegion]=useState('All locations');const featured=properties[0];const shown=properties.filter(p=>region==='All locations'?p.id!==featured.id:p.region===region);return <>
 <section className="page-heading page-wrap"><p className="eyebrow">Past transactions</p><h1>Past sales that reflect <em>real experience.</em></h1><p className="page-lede">A selection of Nathanael’s recent transactions across Kern County, showing the range of homes, locations, and client needs he has worked through.</p><div className="hero-actions"><a className="gold" href="/contact?goal=Buying">Ask About Your Property <ArrowRight/></a><a className="text-link" href="/contact"><span>Contact Nathanael</span><ArrowRight/></a></div></section>
 <section className="svc"><div className="svc-split"><div><p className="eyebrow">A portfolio of past transactions</p><h2>Not a gallery. <em>A record of work.</em></h2></div><p>These properties have sold and are shared to give you a sense of the kinds of homes, locations, and situations Nathanael has worked with. Not every transaction is shown here, but each one reflects a practical, hands-on approach to real estate.</p></div></section>
 <section className="featured-property page-wrap" aria-label="Featured past sale"><PropertyPhoto property={featured} featured/><div className="featured-copy"><p className="eyebrow">Featured transaction · Tehachapi</p><p className="featured-price">{money(featured.price)}</p><h2>{featured.address}</h2><p className="property-location">{featured.city}, CA {featured.zip}</p><PropertyFacts property={featured}/><p className="property-description">{featured.description}</p><p className="sale-date">Sold {soldDate(featured.date)} · {featured.lot}</p><p className="unique-label">What made this property unique:</p><ul className="check-grid unique-grid">{['Acreage and lifestyle appeal','A niche buyer pool','A need for strong presentation and positioning'].map(item=><li key={item}><Check weight="bold"/><span>{item}</span></li>)}</ul><a className="inline-link" href="/contact?goal=Selling">Talk About Your Property <ArrowRight/></a></div></section>
 <section className="portfolio-section page-wrap"><div className="portfolio-controls"><div><p className="eyebrow">Past sales</p><p role="status">{region==='All locations'?properties.length:shown.length} properties{region==='All locations'?' including featured sale':''}</p></div><div className="property-filters" role="group" aria-label="Filter properties by location">{['All locations','Kern County'].map(r=><button key={r} aria-pressed={r===region} onClick={()=>setRegion(r)}>{r}</button>)}</div></div><div className="property-grid">{shown.map(p=><article className="property-card" key={p.id}><PropertyPhoto property={p}/><div className="property-card-body"><div className="price-line"><strong>{money(p.price)}</strong><span>{soldDate(p.date)}</span></div><h2>{p.address}</h2><p className="property-location">{p.city}, CA {p.zip}</p><PropertyFacts property={p}/><p className="context-line">{p.context}</p></div></article>)}</div><p className="source-note">Past transactions and listing photos are shared for reference. These homes have sold and are not currently offered here. Details checked September 6, 2026. Measurements are approximate.</p></section>
 <section className="svc svc--tint"><div className="svc-split"><div><p className="eyebrow">What this experience means</p><h2>What it means <em>for clients.</em></h2></div><p>No two properties are exactly alike. Some require stronger positioning, some require a clearer eye for condition and repairs, and some require a more thoughtful strategy around timing and goals. The value of experience is knowing how to adjust to the situation in front of you.</p></div></section>
 <section className="svc"><div className="testimonial-band"><blockquote><p>“Nathanael brought calm, clarity, and practical advice throughout the sale. We always felt like we understood what was happening and why.”</p></blockquote><p className="t-label">Seller · Kern County</p></div></section>
 <section className="final-cta"><div><p className="eyebrow">Your next step</p><h2>Wondering what your home could be worth,<br/>or what your <em>next move should be?</em></h2></div><div className="actions"><a className="gold" href="/contact?goal=Selling">Ask About Selling <ArrowRight/></a><a className="inline-link" href="/contact">Contact Nathanael <ArrowRight/></a></div></section>
 </>}

export function Contact(){return <>
 <section className="page-heading page-wrap"><p className="eyebrow">Start the conversation here.</p><h1>Start the conversation <em>here.</em></h1><p className="page-lede">Whether you’re ready to move or just beginning to explore your options, reach out with your question, property, or idea. Nathanael works with buyers, sellers, builders, and investors across Kern County.</p><div className="contact-person"><img src="/assets/headshot.webp" alt="Nathanael Harbison"/><div><h2>{agent.name}</h2><p>REALTOR® · Harbison Standard</p><small>DRE #{agent.license}</small></div></div><div className="hero-actions"><a className="gold" href={agent.phoneHref}><Phone/> Call</a><a className="text-link" href={agent.smsHref}><span>Text</span><ArrowRight/></a><a className="text-link" href={'mailto:'+agent.email}><span>Email</span><ArrowRight/></a></div><p className="eyebrow follow-label">Follow along</p><SocialLinks showLabels/></section>
 <section className="svc"><div className="contact-cards"><a className="contact-card" href={agent.phoneHref}><Phone/><div><small>Call Nathanael</small><strong>{agent.phone}</strong></div></a><a className="contact-card" href={agent.smsHref}><ChatCircleText/><div><small>Text Nathanael</small><strong>{agent.phone}</strong></div></a><a className="contact-card" href={'mailto:'+agent.email}><Envelope/><div><small>Email Nathanael</small><strong>{agent.email}</strong></div></a><div className="contact-card"><MapPin/><div><small>Areas served</small><strong>Kern County, California</strong></div></div></div><p className="contact-note">Typical response time: {agent.responseTime}</p></section>
 <section id="quick" className="svc svc--tint"><div className="svc-split"><div><p className="eyebrow">Quick contact form</p><h2>Send a <em>quick message.</em></h2><p className="svc-body">No pressure. No mailing list. Just a direct response from Nathanael.</p></div><QuickForm/></div></section>
 <section id="inquiry" className="inquiry-section"><div><p className="eyebrow">Want to share more details?</p><h2>Tell the <em>full story.</em></h2><p>If you’d like to give more background about your goals, property, timeline, or situation, use the detailed inquiry form below. It takes a few minutes and covers the details that help the first conversation go further.</p><a className="inline-link" href={agent.phoneHref}><Phone/>Prefer to call? {agent.phone}</a></div><LeadForm source="Contact page"/></section>
 <section className="process"><div><p className="eyebrow">What happens next</p><h2>After you <em>reach out.</em></h2></div><ol>{[['Nathanael reviews your message','He looks at your situation, property, or question.'],['You get a direct response','Usually by phone, text, or email based on what you provide.'],['You talk through the next step','No pressure — just a clearer understanding of your options.']].map(([name,copy],i)=><li key={name}><span className="number">0{i+1}</span><h3>{name}</h3><p>{copy}</p></li>)}</ol></section>
 <section className="svc svc--tint"><div className="svc-head"><div><p className="eyebrow">You don’t need to be fully decided</p><h2>Good reasons to <em>reach out.</em></h2></div><p>If any of these sound familiar, start a conversation.</p></div><ul className="check-grid">{['You’re just starting to explore','You’re thinking about selling','You’re unsure whether to repair or sell as-is','You’re considering a build or spec home','You’re looking at an investment property','You’re working with a time-sensitive situation','You’re trying to figure out what makes sense next'].map(item=><li key={item}><Check weight="bold"/><span>{item}</span></li>)}</ul></section>
 <section className="svc"><div className="svc-head"><div><p className="eyebrow">Contact FAQ</p><h2>Quick answers, <em>before you reach out.</em></h2></div></div><div className="faq">{contactFaq.map(({q,a})=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
 <section className="final-cta"><div><p className="eyebrow">Wrapping up</p><h2>A conversation is a good <em>place to start.</em></h2><p>Whether you’re buying, selling, building, or investing, the first step is often just getting clear on the situation. Reach out and start there.</p></div><div className="actions"><a className="gold" href={agent.phoneHref}><Phone/> Call or Text Nathanael</a><a className="inline-link" href="#quick">Send a Message <ArrowRight/></a></div></section>
 </>}