import {HouseLine,Key,Hammer,ChartLineUp,ChatCircle,Clock,Buildings,PaintBrush} from '@phosphor-icons/react';

export const servicePages = {
 '/real-estate': {
  name:'Sell Your Home',category:'Real estate',image:'house',alt:'California home with a landscaped front yard',
  hero:{
   eyebrow:'Selling with clarity',
   heading:'Sell with a clear plan',accent:'and the right perspective.',
   intro:'Whether you\'re planning a move, selling an inherited home, dealing with repairs, or working through a more time-sensitive situation, Nathanael can help you understand your options and choose the right next step.',
   ctas:[{label:'Discuss Your Home',href:'#service-inquiry',kind:'gold'},{label:'Call Nathanael',href:':phone',kind:'link'}],
   caption:'A calm, practical conversation about your home.',
  },
  sections:['who','helps','compare','costs','special','process','faq','testimonial'],
  who:{eyebrow:'Who this page is for',title:'Selling situations',accent:'can look very different.',items:[
   'Planning a standard home sale',
   'Relocating or changing homes',
   'Selling an inherited property',
   'Selling a home that needs repairs',
   'Handling a time-sensitive or difficult situation',
  ]},
  helps:{eyebrow:'What seller support actually looks like',title:'Support from the first',accent:'conversation to close.',tint:true,items:[
   'Pricing and market positioning',
   'Guidance on repairs or preparation',
   'Evaluating as-is vs improvement options',
   'Strategy around timeline and goals',
   'Clear communication through the process',
   'Support from first conversation to close',
  ]},
  compare:{eyebrow:'As-is or improve first',title:'Should you sell as-is',accent:'or improve the home first?',intro:'That depends on the property, the timeline, the likely buyer pool, and the level of preparation that makes sense for your goals. Nathanael\'s real estate experience can help you think through what repairs matter, what updates may be worth considering, and when it makes more sense to move forward as-is.',costContext:'Typical repairs range $5K-$50K+ depending on scope. Recovery on improvements averages 60-80% of cost in Kern County markets, meaning a $20K renovation often adds $12K-$16K in sale price.',a:{title:'Sell as-is when',points:['Speed matters - move in 7-14 days','The home needs more work than you want to take on ($30K+ in repairs)','Simplicity is more important than maximizing every possible dollar','Cash buyers or investors are your likely pool']},b:{title:'Improve first when',points:['Targeted repairs ($5K-$15K) could significantly strengthen marketability','The timeline allows for some preparation (30+ days)','The work is realistic, clear-scope, and recovers well (kitchen, bathroom, cosmetic updates)','You want to appeal to owner-occupants in a broader market']}},
  costs:{eyebrow:'What selling actually costs',title:'Understanding the real',accent:'numbers behind a sale.',intro:'Selling a home isn\'t free, and understanding where money goes helps you set realistic expectations and plan accordingly.',items:[
   {label:'Closing costs (seller)',value:'2-3% of sale price',detail:'On a $400K sale: $8K-$12K. Includes title, escrow, prorations, and agent commission (typically 5-6%).'},
   {label:'Typical repairs',value:'$5K-$50K range',detail:'Minor updates (paint, flooring): $5K-$15K. Significant work (roof, foundation): $30K-$50K+. As-is sales skip these entirely.'},
   {label:'Improvement ROI',value:'60-80% recovery',detail:'A $20K renovation typically adds $12K-$16K in sale price. Strategic work (kitchen, bathroom) recovers best; cosmetic updates recover least.'},
   {label:'Timeline impact',value:'7-30 days on market',detail:'As-is homes often move faster (7-14 days) but at lower prices. Improved homes take longer but attract more competitive offers.'},
   {label:'Holding costs (if timing matters)',value:'$1K-$2K+ per month',detail:'Property taxes, insurance, utilities add up while waiting. Urgent sales may skip improvements entirely to avoid these.'},
  ]},
  special:{eyebrow:'Beyond the standard sale',title:'Some sales come with',accent:'more pressure or complexity.',cards:[
   {title:'Divorce or separation',copy:'A home sale may be one part of a much larger transition. Nathanael can talk through the property, timeline, and what you each need from a sale. Typical closing timeline: 30-60 days. Costs: 2-3% in closing fees on sale price.'},
   {title:'Financial pressure or foreclosure timeline',copy:'When time matters, clarity matters even more. Homes in distress often sell as-is in 7-14 days to investors or cash buyers, recovering 70-85% of market value. Share your timeline and any professionals helping you already.'},
   {title:'Inherited property',copy:'You may have multiple options: rent, improve, or sell. Selling as-is typically takes 14-30 days and sidesteps repair decisions entirely. Many heirs use this route to close out an estate quickly ($8K-$15K in typical closing costs).'},
   {title:'Repairs or deferred maintenance',copy:'A roof replacement ($8K-$15K) or foundation issue ($15K-$50K+) can paralyze sellers. Often, selling as-is to an investor and moving forward makes more financial sense than owner financing the repairs.'},
   {title:'Relocating for work',copy:'Time-sensitive moves benefit from clarity on true market value and realistic timelines. A 30-45 day sale is normal; as-is sales can close in 14-21 days if needed. Budget 2-3% for closing costs plus any overlap holding costs.'},
   {title:'Underwater or short sale',copy:'If the home owes more than market value, the lender must approve any sale. Nathanael can discuss whether a short sale, deed-in-lieu, or waiting for equity recovery makes sense in your situation.'},
  ]},
  process:{eyebrow:'A clear path forward',title:'Simple steps,',accent:'clear next moves.',steps:[
   {name:'Start with your situation',copy:'Share the property, your timing, and your priorities.'},
   {name:'Review the options',copy:'Discuss condition, marketability, and possible next steps.'},
   {name:'Plan the next steps',copy:'Decide whether to prepare, list, or move more quickly.'},
   {name:'Move forward with clarity',copy:'Take the next step with a strategy that fits your goals.'},
  ]},
  faq:{eyebrow:'Seller FAQ',title:'Questions we',accent:'hear often.',items:[
   {q:'Should I repair my home before selling?',a:'It depends on the home, the timeline, and the likely buyer pool. A few targeted repairs can help in some cases; in others, selling as-is is the better move. Nathanael can help you weigh the tradeoffs and understand expected ROI on your investment.'},
   {q:'Can I sell a home as-is?',a:'Yes. As-is sales happen often. Nathanael can help you understand pricing and positioning when a home is sold without repairs. Cash buyers and investors often expect 20-30% discount versus market value, but you move in days instead of months.'},
   {q:'What if my timeline is urgent?',a:'Urgent timelines benefit from clarity even more. Share your dates early; the first step is understanding what\'s realistic in your window. As-is sales can close in 7-14 days, while traditional sales average 30-45 days.'},
   {q:'What if I\'m not ready yet?',a:'That\'s fine. Many conversations start before a decision is made, with no pressure to move forward. You can ask questions first, understand your options, and decide later when you\'re ready.'},
   {q:'Can I reach out before making a final decision?',a:'Absolutely. You can ask questions first and decide later. Nathanael helps sellers who are exploring options and those ready to act - either way, there\'s no cost to understanding your situation and next steps.'},
   {q:'What about timing - how long does selling take?',a:'As-is sales: 7-30 days. Traditional sales with preparation: 30-45 days. Timeline depends on condition, repairs, and buyer pool. Nathanael can help you understand realistic expectations for your situation.'},
  ]},
  testimonial:{quote:'We weren\'t sure whether to fix things up or sell as-is. Nathanael helped us think it through clearly and never made us feel pressured.',label:'Seller - Time-sensitive sale'},
  formTitle:'Start with a conversation',formAccent:'about your home.',
  formCopy:'You don\'t need to have everything figured out before reaching out. A location, rough timing, and a few details are enough to get started.',
  messagePlaceholder:'Your property, its condition, and any timing you want Nathanael to know about...',
  goals:[
   {name:'Planning a home sale',Icon:HouseLine,copy:'Understand my next steps'},
   {name:'A time-sensitive sale',Icon:Clock,copy:'I have an important timeline'},
   {name:'Selling a home that needs repairs',Icon:Hammer,copy:'Discuss the property as it is'},
   {name:'Another selling situation',Icon:ChatCircle,copy:'Talk through my circumstances'},
  ],
 },
 '/investing': {
  name:'Investing',category:'Investing',image:'investing',alt:'A city skyline beneath mountains at sunset',
  hero:{
   eyebrow:'Real estate opportunities',
   heading:'A practical perspective',accent:'on real estate opportunities.',
   intro:'Whether you\'re exploring your first investment property, looking at a flip, or wanting to discuss a possible opportunity with Harbison Standard, Nathanael can help you think through the property, the project, and the fit.',
   ctas:[{label:'Discuss an Investment',href:'#service-inquiry',kind:'gold'},{label:'Review a Deal',href:'#service-inquiry',kind:'link'},{label:'Call Nathanael',href:':phone',kind:'link'}],
   caption:'A property. A project. A conversation.',
  },
  sections:['paths','role','who','scenarios','self','faq','process','credibility'],
  paths:{eyebrow:'What are you looking to do?',title:'Three paths',accent:'into investing.',intro:'Choose the direction that fits you, then explore the details with Nathanael.',cards:[
   {title:'Buy an investment property',copy:'Talk through goals, location, and the type of property that makes sense.',cta:'Discuss an Investment'},
   {title:'Evaluate a flip',copy:'Review the property, renovation scope, budget, and resale potential.',cta:'Review a Deal'},
   {title:'Ask about opportunity with Harbison Standard',copy:'Start a conversation about your interest and whether there\'s a reason to explore it further.',cta:'Start the Conversation'},
  ]},
  role:{eyebrow:'How Nathanael helps you think',title:'Look beyond',accent:'the listing.',body:'A promising opportunity is more than a purchase price. It\'s also condition, renovation scope, timeline, neighborhood fit, exit strategy, and how well the deal matches your goals. Nathanael brings a practical lens to the conversation so you can think through more than just surface numbers.',bullets:[
   'Property potential',
   'Renovation scope',
   'Location fit',
   'Timeline considerations',
   'Hold vs resale thinking',
   'Practical next steps',
  ]},
  who:{eyebrow:'Who this page is for',title:'This may be a fit',accent:'if you are...',tint:true,items:[
   'Exploring your first investment property',
   'Comparing hold vs flip',
   'Looking at a home that needs work',
   'Wanting a second opinion on a deal',
   'Interested in local opportunity conversations',
   'Trying to understand risk and upside more clearly',
  ]},
  scenarios:{eyebrow:'Example conversations',title:'Investor conversations',accent:'Nathanael helps with.',cards:[
   {title:'First rental property',copy:'A buyer looking for a manageable first step into ownership with long-term value in mind.'},
   {title:'Flip opportunity',copy:'A property with upside, but questions around scope, cost, and resale fit.'},
   {title:'Value-add property',copy:'A home that may benefit from strategic improvements before a long-term hold or future sale.'},
   {title:'Local opportunity conversation',copy:'An early-stage discussion around fit, goals, and whether there is a reason to go further.'},
  ]},
  self:{eyebrow:'About the company',title:'Interested in',accent:'Harbison Standard itself?',body:'If you\'re interested in discussing possible future opportunities related to Harbison Standard, you can start with a conversation about your background, interests, and what you\'re looking for. Any specific opportunity would depend on fit, structure, timing, and separate review.'},
  faq:{eyebrow:'Investing FAQ',title:'Investor questions,',accent:'answered plainly.',tint:true,items:[
   {q:'Can a real estate agent help with investment properties?',a:'Yes. Nathanael helps investors think through property potential, renovation scope, location fit, timeline, and whether a deal matches their goals.'},
   {q:'What is a house flip?',a:'A flip is buying a property with the intent to renovate and resell it, often quickly, for a profit. The key details are purchase price, renovation scope, timeline, and resale value.'},
   {q:'Should I hold a rental property or flip it?',a:'It depends on your goals, capital, and timeline. Holding typically trades cash flow and appreciation for slower growth, while a flip trades renovation work for a faster return. Nathanael can help you compare the two.'},
   {q:'Can I ask about investing in Harbison Standard?',a:'You can start with a conversation about your background and interests. Any specific opportunity would depend on fit, structure, timing, and separate review.'},
   {q:'How do investors get in touch?',a:'Call or text (661) 472-7499 or send a message through the inquiry form. Let Nathanael know the property or opportunity you\'re considering.'},
  ]},
  process:{eyebrow:'How it starts',title:'Start with the property, project,',accent:'or goal.',tint:true,steps:[
   {name:'Share the opportunity or idea',copy:'Bring a property, address, goal, or general direction.'},
   {name:'Review the practical details',copy:'Talk through condition, budget, timing, and likely path.'},
   {name:'Decide whether it makes sense',copy:'Move forward, adjust, or walk away with more clarity.'},
  ]},
  credibility:{eyebrow:'Why this perspective helps',title:'Investors value',accent:'a practical eye.',items:[
   'Property experience',
   'Real estate experience',
   'Practical thinking',
   'Straightforward communication',
   'Local market understanding',
  ]},
  formTitle:'Have a deal, a property,',formAccent:'or an idea to talk through?',
  formCopy:'Tell Nathanael which path interests you. You can start with a general idea or a specific property you\'re considering.',
  messagePlaceholder:'Your investment interests, a property or project, budget range, and experience...',
  goals:[
   {name:'Real estate investing',Icon:ChartLineUp,copy:'Explore investment properties'},
   {name:'Investing in Harbison Standard',Icon:Buildings,copy:'Ask about the company'},
   {name:'Buying, restoring, and flipping a home',Icon:PaintBrush,copy:'Discuss my own renovation project'},
  ],
 },
};
