import {HouseLine,Key,Hammer,ChartLineUp,ChatCircle,Clock,Buildings,PaintBrush} from '@phosphor-icons/react';

export const servicePages = {
 '/real-estate': {
  name:'Sell Your Home',category:'Real estate',image:'house',alt:'California home with a landscaped front yard',
  hero:{
   eyebrow:'Selling with clarity',
   heading:'Sell with a clear plan',accent:'and the right perspective.',
   intro:'Whether you’re planning a move, selling an inherited home, dealing with repairs, or working through a more time-sensitive situation, Nathanael can help you understand your options and choose the right next step.',
   ctas:[{label:'Discuss Your Home',href:'#service-inquiry',kind:'gold'},{label:'Call Nathanael',href:':phone',kind:'link'}],
   caption:'A calm, practical conversation about your home.',
  },
  sections:['who','helps','compare','special','process','faq','testimonial'],
  who:{eyebrow:'Who this page is for',title:'Selling situations',accent:'can look very different.',items:[
   'Planning a standard home sale',
   'Relocating or changing homes',
   'Selling an inherited property',
   'Selling a home that needs repairs',
   'Handling a time-sensitive or difficult situation',
  ]},
  helps:{eyebrow:'What seller support actually looks like',title:'Support from the first',accent:'conversation to close.',tint:true,items:[
   'Pricing and market positioning',
   'Guidance on repairs or preparation',
   'Evaluating as-is vs improvement options',
   'Strategy around timeline and goals',
   'Clear communication through the process',
   'Support from first conversation to close',
  ]},
  compare:{eyebrow:'As-is or improve first',title:'Should you sell as-is',accent:'or improve the home first?',intro:'That depends on the property, the timeline, the likely buyer pool, and the level of preparation that makes sense for your goals. Nathanael’s construction background can help you think through what repairs matter, what updates may be worth considering, and when it makes more sense to move forward as-is.',a:{title:'Sell as-is when',points:['Speed matters','The home needs more work than you want to take on','Simplicity is more important than maximizing every possible dollar']},b:{title:'Improve first when',points:['A few targeted repairs could significantly strengthen marketability','The timeline allows for some preparation','The work is realistic and worth the effort']}},
  special:{eyebrow:'Beyond the standard sale',title:'Some sales come with',accent:'more pressure or complexity.',cards:[
   {title:'Divorce or separation',copy:'A home sale may be one part of a much larger transition. Nathanael can talk through the property and what you need from a sale.'},
   {title:'Financial pressure or foreclosure timeline',copy:'When time matters, clarity matters even more. Share your timing and the professionals already helping you.'},
   {title:'Inherited property',copy:'Support for deciding what to do with a home you didn’t plan to take on.'},
   {title:'Repairs or deferred maintenance',copy:'Talk through whether to fix, update, or sell the home as-is.'},
  ]},
  process:{eyebrow:'A clear path forward',title:'Simple steps,',accent:'clear next moves.',steps:[
   {name:'Start with your situation',copy:'Share the property, your timing, and your priorities.'},
   {name:'Review the options',copy:'Discuss condition, marketability, and possible next steps.'},
   {name:'Build the plan',copy:'Decide whether to prepare, list, or move more quickly.'},
   {name:'Move forward with clarity',copy:'Take the next step with a strategy that fits your goals.'},
  ]},
  faq:{eyebrow:'Seller FAQ',title:'Questions we',accent:'hear often.',items:[
   {q:'Should I repair my home before selling?',a:'It depends on the home, the timeline, and the likely buyer pool. A few targeted repairs can help in some cases; in others, selling as-is is the better move. Nathanael can help you weigh the tradeoffs.'},
   {q:'Can I sell as-is?',a:'Yes. As-is sales happen often. Nathanael can help you understand pricing and positioning when a home is sold without repairs.'},
   {q:'What if my timeline is urgent?',a:'Urgent timelines benefit from clarity even more. Reach out with your dates — the first step is understanding what’s realistic in your window.'},
   {q:'What if I’m not ready yet?',a:'That’s fine. Many conversations start before a decision is made. There’s no pressure to move forward until you’re ready.'},
   {q:'Can I reach out before making a final decision?',a:'Absolutely. You can ask questions first and decide later.'},
  ]},
  testimonial:{quote:'We weren’t sure whether to fix things up or sell as-is. Nathanael helped us think it through clearly and never made us feel pressured.',label:'Seller · Time-sensitive sale'},
  formTitle:'Start with a conversation',formAccent:'about your home.',
  formCopy:'You don’t need to have everything figured out before reaching out. A location, rough timing, and a few details are enough to get started.',
  messagePlaceholder:'Your property, its condition, and any timing you want Nathanael to know about…',
  goals:[
   {name:'Planning a home sale',Icon:HouseLine,copy:'Understand my next steps'},
   {name:'A time-sensitive sale',Icon:Clock,copy:'I have an important timeline'},
   {name:'Selling a home that needs repairs',Icon:Hammer,copy:'Discuss the property as it is'},
   {name:'Another selling situation',Icon:ChatCircle,copy:'Talk through my circumstances'},
  ],
 },
 '/development': {
  name:'Development',category:'Development',image:'development',alt:'Timber framing inside a home under construction',
  hero:{
   eyebrow:'Building, buying new, or land',
   heading:'Guidance for building, buying new,',accent:'or evaluating land.',
   intro:'Whether you want to build a home, explore a spec home, or understand the potential of a piece of land, Nathanael can help you think through the real estate side with a practical, construction-aware perspective.',
   ctas:[{label:'Discuss a Build',href:'#service-inquiry',kind:'gold'},{label:'Ask About Land',href:'#service-inquiry',kind:'link'},{label:'Call Nathanael',href:':phone',kind:'link'}],
   caption:'A practical view of building and new construction.',
  },
  sections:['role','paths','compare','considerations','mistakes','proof','process'],
  role:{eyebrow:'How Nathanael helps',title:'A builder’s perspective',accent:'on the real estate side.',body:'Nathanael helps clients think through the practical side of building and new construction: location, land, property fit, timing, goals, and the broader real estate picture. He brings a builder’s perspective into the conversation so clients can ask better questions and move forward more confidently.',bullets:[
   'Explore land opportunities',
   'Compare building vs buying',
   'Discuss spec home options',
   'Think through goals, budget, and timing',
   'Evaluate next steps before committing',
  ]},
  paths:{eyebrow:'Choose your path',title:'Three common',accent:'starting points.',intro:'Each path starts with a conversation about what you want and what makes sense for your situation.',cards:[
   {title:'Build a home',copy:'For people with a vision, a location in mind, or land already owned.',cta:'Talk About Building'},
   {title:'Buy a spec home',copy:'For people who want newer construction with a simpler, faster path.',cta:'Explore Spec Homes'},
   {title:'Evaluate land',copy:'For people considering a parcel and wanting to understand the bigger picture before moving forward.',cta:'Discuss a Parcel'},
  ]},
  compare:{eyebrow:'Build vs buy new',title:'Build a home,',accent:'or buy a spec home?',intro:'Both paths get you new construction. The right one depends on how much control you want and how quickly you want to move.',a:{title:'Build a home if you want',points:['More customization','More control over the result','Flexibility in design and layout','A longer planning horizon']},b:{title:'Buy a spec home if you want',points:['Newer construction sooner','Less decision fatigue','A simpler purchase path','Move-in readiness']}},
  considerations:{eyebrow:'The early questions',title:'Think through these',accent:'before you commit.',tint:true,items:[
   'Where you want to live',
   'Whether you already own land',
   'How custom the home needs to be',
   'Your timeline',
   'Your rough budget range',
   'Whether you want to build or buy new',
  ]},
  mistakes:{eyebrow:'Common mistakes',title:'What Nathanael sees',accent:'before building or buying land.',items:[
   'Falling in love with land before understanding the full picture',
   'Underestimating site and prep costs',
   'Focusing only on finishes instead of function',
   'Not thinking through timing early',
   'Moving forward without enough clarity around goals',
  ]},
  proof:{eyebrow:'From the ground up',title:'The kind of work',accent:'behind the conversations.',body:'From framing to finished homes, these are examples of the building world Nathanael brings to discussions about land, builds, and new construction.',images:[
   {src:'/assets/development.webp',alt:'Timber framing inside a home under construction',caption:'Framing in progress'},
   {src:'/assets/house.webp',alt:'A completed California home with a landscaped front yard',caption:'A completed home'},
   {src:'/assets/property-front.webp',alt:'The front of a property and home site',caption:'A property start'},
  ]},
  process:{eyebrow:'How it starts',title:'How the conversation',accent:'typically begins.',tint:true,steps:[
   {name:'Share the idea',copy:'Tell Nathanael what you want to build, buy, or evaluate.'},
   {name:'Review the practical picture',copy:'Talk through location, property type, goals, budget, and timing.'},
   {name:'Identify the next best move',copy:'Move toward a clearer decision with less guesswork.'},
  ]},
  formTitle:'Thinking about building, buying new,',formAccent:'or exploring land?',
  formCopy:'Tell Nathanael whether you’re looking to build a home, buy a spec home, or evaluate land. A preferred area and a rough budget are enough to start.',
  messagePlaceholder:'Your ideal home, preferred area, budget range, and whether you already own land…',
  goals:[
   {name:'Building a home',Icon:Hammer,copy:'Bring my plans to life'},
   {name:'Buying a spec home',Icon:Key,copy:'Find a new home built for sale'},
   {name:'Exploring land for a home',Icon:HouseLine,copy:'Talk about a parcel or location'},
  ],
 },
 '/investing': {
  name:'Investing',category:'Investing',image:'investing',alt:'A city skyline beneath mountains at sunset',
  hero:{
   eyebrow:'Real estate opportunities',
   heading:'A practical perspective',accent:'on real estate opportunities.',
   intro:'Whether you’re exploring your first investment property, looking at a flip, or wanting to discuss a possible opportunity with Harbison Standard, Nathanael can help you think through the property, the project, and the fit.',
   ctas:[{label:'Discuss an Investment',href:'#service-inquiry',kind:'gold'},{label:'Review a Deal',href:'#service-inquiry',kind:'link'},{label:'Call Nathanael',href:':phone',kind:'link'}],
   caption:'A property. A project. A conversation.',
  },
  sections:['paths','role','who','scenarios','self','process','credibility'],
  paths:{eyebrow:'What are you looking to do?',title:'Three paths',accent:'into investing.',intro:'Choose the direction that fits you, then explore the details with Nathanael.',cards:[
   {title:'Buy an investment property',copy:'Talk through goals, location, and the type of property that makes sense.',cta:'Discuss an Investment'},
   {title:'Evaluate a flip',copy:'Review the property, renovation scope, budget, and resale potential.',cta:'Review a Deal'},
   {title:'Ask about opportunity with Harbison Standard',copy:'Start a conversation about your interest and whether there’s a reason to explore it further.',cta:'Start the Conversation'},
  ]},
  role:{eyebrow:'How Nathanael helps you think',title:'Look beyond',accent:'the listing.',body:'A promising opportunity is more than a purchase price. It’s also condition, renovation scope, timeline, neighborhood fit, exit strategy, and how well the deal matches your goals. Nathanael brings a practical lens to the conversation so you can think through more than just surface numbers.',bullets:[
   'Property potential',
   'Renovation scope',
   'Location fit',
   'Timeline considerations',
   'Hold vs resale thinking',
   'Practical next steps',
  ]},
  who:{eyebrow:'Who this page is for',title:'This may be a fit',accent:'if you are…',tint:true,items:[
   'Exploring your first investment property',
   'Comparing hold vs flip',
   'Looking at a home that needs work',
   'Wanting a second opinion on a deal',
   'Interested in local opportunity conversations',
   'Trying to understand risk and upside more clearly',
  ]},
  scenarios:{eyebrow:'Example conversations',title:'Investor conversations',accent:'Nathanael helps with.',cards:[
   {title:'First rental property',copy:'A buyer looking for a manageable first step into ownership with long-term value in mind.'},
   {title:'Flip opportunity',copy:'A property with upside, but questions around scope, cost, and resale fit.'},
   {title:'Value-add property',copy:'A home that may benefit from strategic improvements before a long-term hold or future sale.'},
   {title:'Local opportunity conversation',copy:'An early-stage discussion around fit, goals, and whether there is a reason to go further.'},
  ]},
  self:{eyebrow:'About the company',title:'Interested in',accent:'Harbison Standard itself?',body:'If you’re interested in discussing possible future opportunities related to Harbison Standard, you can start with a conversation about your background, interests, and what you’re looking for. Any specific opportunity would depend on fit, structure, timing, and separate review.'},
  process:{eyebrow:'How it starts',title:'Start with the property, project,',accent:'or goal.',tint:true,steps:[
   {name:'Share the opportunity or idea',copy:'Bring a property, address, goal, or general direction.'},
   {name:'Review the practical details',copy:'Talk through condition, budget, timing, and likely path.'},
   {name:'Decide whether it makes sense',copy:'Move forward, adjust, or walk away with more clarity.'},
  ]},
  credibility:{eyebrow:'Why this perspective helps',title:'Investors value',accent:'a practical eye.',items:[
   'Construction background',
   'Real estate experience',
   'Practical thinking',
   'Straightforward communication',
   'Local market understanding',
  ]},
  formTitle:'Have a deal, a property,',formAccent:'or an idea to talk through?',
  formCopy:'Tell Nathanael which path interests you. You can start with a general idea or a specific property you’re considering.',
  messagePlaceholder:'Your investment interests, a property or project, budget range, and experience…',
  goals:[
   {name:'Real estate investing',Icon:ChartLineUp,copy:'Explore investment properties'},
   {name:'Investing in Harbison Standard',Icon:Buildings,copy:'Ask about the company'},
   {name:'Buying, restoring, and flipping a home',Icon:PaintBrush,copy:'Discuss my own renovation project'},
  ],
 },
};